<template>
  <div>
    <knowledge-graph :word="word" :relationship="relationship" :subjectName="subjectName"></knowledge-graph>
  </div>
</template>

<script>
import knowledgeGraph from '@/components/works/knowledgeGraph'
export default {
  components: { knowledgeGraph },
  data() {
    return {
      subjectName: '艺术',
      word: [
        '社会主 义',
        '不同舞种的舞蹈姿态与基本动作',
        '中华民族追求独立解放和党团结带领人民进行革命、建设、改革',
        '守规则、负责任等良好品质',
        '音 乐',
        '某件物 品',
        '富有个性和创意的二度创作及表现形式的创新',
        '“教育戏剧”“教育剧场”的方法',
        '较浓厚的兴趣',
        '社会责任感',
        '中华民族自豪感',
        '工艺品',
        '参与多种与音乐相关的艺术表现活动，展现自己的个性化理解和创意',
        '对中国音乐文化',
        '简单的音 乐作品',
        '音乐的情绪与情感',
        '中国戏曲艺术审美特征',
        '戏 剧',
        '平面、立体或动态等表现形式的美术作 品',
        '声音与音乐',
        '影视（含数字媒体艺术）作品的形态特征',
        '规则',
        '民族文化智慧',
        '身体语言',
        '爱党、爱国、爱家乡的情感',
        '工艺 师敬业、专注和精益求精的工匠精神',
        '国家认同 感、归属感、责任感和使命感',
        '文化自信',
        '美',
        '“实用与美观相结合"的设计原则',
        '对他人及自我的理解',
        '伟大建党精神',
        '影视（含数字媒体艺术）',
        '中外戏剧艺术史的基本常识',
        '尊 重、理解和包容的态度',
        '实践经验',
        '文 化差异',
        '剧目',
        '对他人及自我',
        '世界美术的多样性和差异性',
        '文化遗产',
        '美术各种问题',
        '社会主义',
        '传统或现代的工具、材料和媒介',
        '中国传统工艺是中华民族文化艺术的瑰宝',
        '传统与现代的工具、材料和媒介，以及习得的美术知 识、技能和思维方式',
        '开放包容的心态和人类命运共同体意识',
        '实用功能与审美价值',
        '世界音乐文化的多样性',
        '初步的音 乐欣赏与评述能力',
        '独 特的作用',
        '校园微电影',
        '综合融通',
        '第二学段学生',
        '民族精神、时代精神等',
        '脚本',
        '表达自己独特的感受和想法',
        '音乐与姊妹艺术、其他学科，以及个人、自然、生活、社会、科技的广泛联系',
        '对伟 大祖国、中华民族的情感',
        '设计能改善和美化我们的生活',
        '个人、自然、生活、社会、科技',
        '兴趣',
        '自己的所见所闻、所感所想',
        '正',
        '影视（含数字媒体艺术）与真实世界、虚拟世界的联系',
        '党',
        '自己的改进意见',
        '对影视（含数字媒体艺术）作品',
        '红色基因',
        '第四学段学生',
        '影视（含数字媒体艺术）作品',
        '规则意识、责任意识和学习意志力等',
        '简单的数字设备和软件',
        '对自然与社会的感受、思考和认识',
        '自己的情感',
        '较丰富的想象力和创造力',
        '艺术',
        '音乐',
        '美术产生的背景及不同时代、地区、民族和国家的美术特 征',
        '中华优秀传统文化、革命文化、社会主义先 进文化',
        '美存在于我们周边',
        '所见所闻、所感所想',
        '中国音乐文化中的中华美育精神和民族审美特质',
        '环境规划',
        '多种艺术手段',
        '中外戏剧艺术的不 同文化背景',
        '创意实践能力和艺术表现水平',
        '积极乐观的态度',
        '不同的工具、材料和技能',
        '自己的想法和感受',
        '我们的生活',
        '社会生活和社会文化中的音乐现象',
        '社会责任',
        '不同音乐表现特征的差异与联系',
        '自主学习能力和团队合作能力',
        '戏曲',
        '简单评述',
        '对我国优秀民族舞蹈文化的学习与传承',
        '第三学段学生',
        '规则意识和合作意识',
        '音乐的感性特征和审美特质',
        '中外美术作品的魅力',
        '自己的想法和情 感',
        '物品的特点',
        '美好事 物的',
        '校园现实生活',
        '不同体裁和风格的舞蹈',
        '初步表达观剧感受和见解的能力',
        '作品',
        '音乐的感性特 征和审美特质',
        '学科，以及信息科技等课程的学习',
        '歌',
        '自己独特的感受和想法',
        '一定的想象力和创造力',
        '乐观的态度以及对身边人的友爱之情',
        '其他艺术学科，以及信息科技等课程',
        '文 化自信',
        '传统工艺品或文创产品',
        '音乐的基本特征',
        '身边的美',
        '人民进行革命、建设、改革',
        '身心健康成长',
        '，以及个人、自然、生活、社会、科技的联系',
        '班级或小组开展的美术与姊妹艺术及其他学科相结 合的造型游戏活动',
        '不同的工具和材料',
        '比较完整的短小音乐作品',
        '丰富的音乐情绪与情感体验',
        '传统工艺',
        '戏剧（含戏曲）活动',
        '影视（含数字媒体艺术）作品的主要类型、风格与流派',
        '对美好事物',
        '音乐的艺术形象',
        '社会责任意识',
        '中外舞蹈艺术特色',
        '音乐情绪',
        '音乐作品',
        '舞蹈美的丰富性',
        '运用多种艺术手段进行戏剧演出的基本能力',
        '实用与美观',
        '文化视野',
        '对音乐感 性特征和审美特质的感知、体验与理解',
        '初步欣赏和分析',
        '个人',
        '个性和创意',
        '工 艺品',
        '想象力和创造力',
        '传统工艺品',
        '与同伴合作的意识和团队精神',
        '文 化',
        '乐观的态度以及对美好事 物的关爱之情',
        '继承与发展文化遗产是我们的责任',
        '对音乐的兴趣',
        '自己的发现和感受',
        '剧',
        '多种艺术表现形式',
        '造型游戏活动',
        '艺术家的作品',
        '表现形式',
        '戏剧',
        '美好事 物',
        '对我国优秀民族舞蹈文化',
        '观剧感受和见解',
        '中国戏曲艺术所具有的独特的审美特征',
        '自己的想法',
        '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏剧表演等艺术活动',
        '造型元素、形式原理和欣赏方法',
        '世界多元音乐文化',
        '不同的工具、材料和媒介',
        '对中国音乐文化的了解和喜爱之情',
        '艺术表现能力',
        '艺术表现的乐趣',
        '综合探索与学习迁移的能力',
        '家乡',
        '影视艺术思维、数字媒体思维、信息思维和科技思维等',
        '爱党、爱国、爱社会主 义的情感和乐观的态度，以及对美好事物的热爱之情',
        '对戏剧（含戏曲）艺术作品',
        '非物质文化遗产的含义',
        '自己的个性化理解和创意',
        '中国音乐文化',
        '装饰和美化',
        '创造性思维能力',
        '情感、观念和想象',
        '对音乐感 性特征和审美特质',
        '物品',
        '平面、立体或动态等表现形式的美术作品',
        '创意表达能力',
        '创意',
        '自信心',
        '舞蹈',
        '文化自 信',
        '社会主义核心价值观',
        '影视（含数字媒体艺术）作品的制作流程',
        '好奇心和探究欲',
        '简单评价',
        '戏剧编演的方法',
        '传统工艺“守正创新"的内涵与意义',
        '良好的欣赏习惯',
        '一定的戏剧应 用活动',
        '对音乐的浓厚兴趣',
        '第一学段学生',
        '多种与音乐相关的艺术表现活动',
        '数字媒体艺术',
        '作品中蕴含的爱国主义、集体主义',
        '音乐表现活动',
        '交流与合作能力',
        '美术对个人发展、社会进步及构建人类命运共同体具有独 特的作用',
        '审美和人文素养',
        '美术',
        '不同音乐的表达方式',
        '世界不同国家和地区的美术作品',
        '不同艺术的主要表现形式、表现手段和审美特征',
        '人类命运共同体',
        '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用',
        '制作工 艺品',
        '爱党、爱国、爱社会主义的情感',
        '美术知 识、技能和思维方式',
        '中国音乐文化和世界多元音乐文化',
        '“设计满足实用功能与审美价值，传递社会责任”的设计原则',
        '影视（含数字媒体艺术）的基本创作技巧和艺术语言',
        '对音乐作品和音乐活动',
        '音乐的思想感情和内涵意蕴',
        '影视（含数字媒体艺术）在传承和弘扬中华优秀传统文化、革命文化、社会主义先 进文化，感悟伟大建党精神过程中的重要作用',
        '环境',
        '戏剧演出',
        '音乐欣赏和评述能力',
        '创意活动',
        '创新思维能力',
        '影视（含数字媒体艺术）与真实世界、虚拟世界',
        '综 合探索与学习迁移的能力',
        '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏 剧表演等艺术活动',
      ],
      relationship: [
        { word1: '第一学段学生', word2: '音乐的情绪与情感', dependency: '体验' },
        { word1: '第一学段学生', word2: '音乐的基本特征', dependency: '了解' },
        { word1: '第一学段学生', word2: '音乐的艺术形象', dependency: '感知' },
        { word1: '第一学段学生', word2: '兴趣', dependency: '产生' },
        { word1: '第一学段学生', word2: '爱党、爱国、爱家乡的情感', dependency: '唤起' },
        { word1: '第一学段学生', word2: '党', dependency: '爱' },
        { word1: '第一学段学生', word2: '家乡', dependency: '爱' },
        { word1: '第一学段学生', word2: '乐观的态度以及对身边人的友爱之情', dependency: '具有' },
        { word1: '第一学段学生', word2: '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏 剧表演等艺术活动', dependency: '参与' },
        { word1: '第一学段学生', word2: '歌', dependency: '表演' },
        { word1: '第一学段学生', word2: '戏 剧', dependency: '表演' },
        { word1: '第一学段学生', word2: '实践经验', dependency: '积累' },
        { word1: '第一学段学生', word2: '艺术表现的乐趣', dependency: '享受' },
        { word1: '第一学段学生', word2: '艺术', dependency: '表现' },
        { word1: '第一学段学生', word2: '艺术', dependency: '实践' },
        { word1: '第一学段学生', word2: '规则意识和合作意识', dependency: '建立' },
        { word1: '第一学段学生', word2: '好奇心和探究欲', dependency: '有' },
        { word1: '第一学段学生', word2: '声音与音乐', dependency: '探究' },
        { word1: '第一学段学生', word2: '自己的想法和感受', dependency: '表达' },
        { word1: '第一学段学生', word2: '自己的想法和感受', dependency: '感受' },
        { word1: '第一学段学生', word2: '中国音乐文化和世界多元音乐文化', dependency: '了解' },
        { word1: '第一学段学生', word2: '自己的发现和感受', dependency: '分享' },
        { word1: '第一学段学生', word2: '自己的发现和感受', dependency: '交流' },
        { word1: '第一学段学生', word2: '自己的发现和感受', dependency: '发现' },
        { word1: '第一学段学生', word2: '身边的美', dependency: '感知' },
        { word1: '第一学段学生', word2: '美存在于我们周边', dependency: '认识' },
        { word1: '第一学段学生', word2: '美存在于我们周边', dependency: '形成' },
        { word1: '第一学段学生', word2: '美', dependency: '欣赏' },
        { word1: '第一学段学生', word2: '不同的工具、材料和媒介', dependency: '使用' },
        { word1: '第一学段学生', word2: '所见所闻、所感所想', dependency: '表达' },
        { word1: '第一学段学生', word2: '物品', dependency: '使用' },
        { word1: '第一学段学生', word2: '物品的特点', dependency: '了解' },
        { word1: '第一学段学生', word2: '某件物 品', dependency: '设计' },
        { word1: '第一学段学生', word2: '自己的改进意见', dependency: '提出' },
        { word1: '第一学段学生', word2: '装饰和美化', dependency: '进行' },
        { word1: '第一学段学生', word2: '不同的工具、材料和媒介', dependency: '利用' },
        { word1: '第一学段学生', word2: '传统工艺', dependency: '体验' },
        { word1: '第一学段学生', word2: '制作工 艺品', dependency: '学习' },
        { word1: '第一学段学生', word2: '工 艺品', dependency: '制作' },
        { word1: '第一学段学生', word2: '中国传统工艺是中华民族文化艺术的瑰宝', dependency: '知道' },
        { word1: '第一学段学生', word2: '中华民族自豪感', dependency: '增强' },
        { word1: '第一学段学生', word2: '班级或小组开展的美术与姊妹艺术及其他学科相结 合的造型游戏活动', dependency: '参与' },
        { word1: '第一学段学生', word2: '造型游戏活动', dependency: '结 合' },
        { word1: '第一学段学生', word2: '综合探索与学习迁移的能力', dependency: '形成' },
        { word1: '第一学段学生', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第二学段学生', word2: '丰富的音乐情绪与情感体验', dependency: '具有' },
        { word1: '第二学段学生', word2: '音乐情绪', dependency: '丰富' },
        { word1: '第二学段学生', word2: '音乐情绪', dependency: '体验' },
        { word1: '第二学段学生', word2: '音乐情绪', dependency: '共鸣' },
        { word1: '第二学段学生', word2: '爱党、爱国、爱社会主义的情感', dependency: '焕发' },
        { word1: '第二学段学生', word2: '党', dependency: '爱' },
        { word1: '第二学段学生', word2: '社会主义', dependency: '爱' },
        { word1: '第二学段学生', word2: '乐观的态度以及对美好事 物的关爱之情', dependency: '具有' },
        { word1: '第二学段学生', word2: '美好事 物', dependency: '关爱' },
        { word1: '第二学段学生', word2: '美好事 物的', dependency: '感知' },
        { word1: '第二学段学生', word2: '美好事 物', dependency: '体验' },
        { word1: '第二学段学生', word2: '音乐的感性特征和审美特质', dependency: '了解' },
        { word1: '第二学段学生', word2: '良好的欣赏习惯', dependency: '养成' },
        { word1: '第二学段学生', word2: '简单评价', dependency: '进行' },
        { word1: '第二学段学生', word2: '对音乐作品和音乐活动', dependency: '评价' },
        { word1: '第二学段学生', word2: '对音乐的兴趣', dependency: '增强' },
        { word1: '第二学段学生', word2: '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏剧表演等艺术活动', dependency: '进行' },
        { word1: '第二学段学生', word2: '戏剧', dependency: '表演' },
        { word1: '第二学段学生', word2: '表达自己独特的感受和想法', dependency: '乐于' },
        { word1: '第二学段学生', word2: '自己独特的感受和想法', dependency: '表达' },
        { word1: '第二学段学生', word2: '规则意识、责任意识和学习意志力等', dependency: '增强' },
        { word1: '第二学段学生', word2: '交流与合作能力', dependency: '发展' },
        { word1: '第二学段学生', word2: '好奇心和探究欲', dependency: '保持' },
        { word1: '第二学段学生', word2: '好奇心和探究欲', dependency: '表演' },
        { word1: '第二学段学生', word2: '艺术', dependency: '编创' },
        { word1: '第二学段学生', word2: '艺术', dependency: '创造' },
        { word1: '第二学段学生', word2: '艺术', dependency: '活动' },
        { word1: '第二学段学生', word2: '个性和创意', dependency: '展现' },
        { word1: '第二学段学生', word2: '对中国音乐文化的了解和喜爱之情', dependency: '增进' },
        { word1: '第二学段学生', word2: '对中国音乐文化', dependency: '了解' },
        { word1: '第二学段学生', word2: '世界多元音乐文化', dependency: '了解' },
        { word1: '第二学段学生', word2: '文化视野', dependency: '开阔' },
        { word1: '第二学段学生', word2: '社会生活和社会文化中的音乐现象', dependency: '关注' },
        { word1: '第二学段学生', word2: '个人、自然、生活、社会、科技', dependency: '联系' },
        { word1: '第二学段学生', word2: '，以及个人、自然、生活、社会、科技的联系', dependency: '了解' },
        { word1: '第二学段学生', word2: '造型元素、形式原理和欣赏方法', dependency: '运用' },
        { word1: '第二学段学生', word2: '艺术家的作品', dependency: '欣赏' },
        { word1: '第二学段学生', word2: '艺术家的作品', dependency: '评述' },
        { word1: '第二学段学生', word2: '中外美术作品的魅力', dependency: '感受' },
        { word1: '第二学段学生', word2: '传统或现代的工具、材料和媒介', dependency: '运用' },
        { word1: '第二学段学生', word2: '平面、立体或动态等表现形式的美术作品', dependency: '创作' },
        { word1: '第二学段学生', word2: '自己的所见所闻、所感所想', dependency: '表达' },
        { word1: '第二学段学生', word2: '自己的所见所闻、所感所想', dependency: '交流' },
        { word1: '第二学段学生', word2: '“实用与美观相结合"的设计原则', dependency: '了解' },
        { word1: '第二学段学生', word2: '实用与美观', dependency: '结合' },
        { word1: '第二学段学生', word2: '物品', dependency: '设计' },
        { word1: '第二学段学生', word2: '设计能改善和美化我们的生活', dependency: '体会' },
        { word1: '第二学段学生', word2: '我们的生活', dependency: '改善' },
        { word1: '第二学段学生', word2: '我们的生活', dependency: '美化' },
        { word1: '第二学段学生', word2: '不同的工具、材料和技能', dependency: '利用' },
        { word1: '第二学段学生', word2: '传统工艺品', dependency: '制作' },
        { word1: '第二学段学生', word2: '工艺 师敬业、专注和精益求精的工匠精神', dependency: '学习' },
        { word1: '第二学段学生', word2: '美术', dependency: '融合' },
        { word1: '第二学段学生', word2: '美术各种问题', dependency: '探究' },
        { word1: '第二学段学生', word2: '综 合探索与学习迁移的能力', dependency: '提高' },
        { word1: '第二学段学生', word2: '综 合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第三学段学生', word2: '音乐的思想感情和内涵意蕴', dependency: '领悟' },
        { word1: '第三学段学生', word2: '爱党、爱国、爱社会主 义的情感和乐观的态度，以及对美好事物的热爱之情', dependency: '增强' },
        { word1: '第三学段学生', word2: '党', dependency: '爱' },
        { word1: '第三学段学生', word2: '社会主 义', dependency: '爱' },
        { word1: '第三学段学生', word2: '社会主 义', dependency: '美好' },
        { word1: '第三学段学生', word2: '对美好事物', dependency: '热爱' },
        { word1: '第三学段学生', word2: '对音乐感 性特征和审美特质的感知、体验与理解', dependency: '加深' },
        { word1: '第三学段学生', word2: '对音乐感 性特征和审美特质', dependency: '感知' },
        { word1: '第三学段学生', word2: '对音乐感 性特征和审美特质', dependency: '理解' },
        { word1: '第三学段学生', word2: '音乐欣赏和评述能力', dependency: '提高' },
        { word1: '第三学段学生', word2: '音乐', dependency: '欣赏' },
        { word1: '第三学段学生', word2: '音乐', dependency: '评述' },
        { word1: '第三学段学生', word2: '较浓厚的兴趣', dependency: '有' },
        { word1: '第三学段学生', word2: '参与多种与音乐相关的艺术表现活动，展现自己的个性化理解和创意', dependency: '乐于' },
        { word1: '第三学段学生', word2: '多种与音乐相关的艺术表现活动', dependency: '参与' },
        { word1: '第三学段学生', word2: '多种与音乐相关的艺术表现活动', dependency: '表现' },
        { word1: '第三学段学生', word2: '多种与音乐相关的艺术表现活动', dependency: '活动' },
        { word1: '第三学段学生', word2: '自己的个性化理解和创意', dependency: '展现' },
        { word1: '第三学段学生', word2: '自己的个性化理解和创意', dependency: '理解' },
        { word1: '第三学段学生', word2: '交流与合作能力', dependency: '增强' },
        { word1: '第三学段学生', word2: '守规则、负责任等良好品质', dependency: '养成' },
        { word1: '第三学段学生', word2: '规则', dependency: '守' },
        { word1: '第三学段学生', word2: '自己的情感', dependency: '选用' },
        { word1: '第三学段学生', word2: '音乐作品', dependency: '合适' },
        { word1: '第三学段学生', word2: '自己的情感', dependency: '表达' },
        { word1: '第三学段学生', word2: '简单的音 乐作品', dependency: '编创' },
        { word1: '第三学段学生', word2: '简单的音 乐作品', dependency: '展示' },
        { word1: '第三学段学生', word2: '一定的想象力和创造力', dependency: '具有' },
        { word1: '第三学段学生', word2: '中国音乐文化中的中华美育精神和民族审美特质', dependency: '理解' },
        { word1: '第三学段学生', word2: '文 化自信', dependency: '增强' },
        { word1: '第三学段学生', word2: '文 化', dependency: '自信' },
        { word1: '第三学段学生', word2: '世界多元音乐文化', dependency: '了解' },
        { word1: '第三学段学生', word2: '世界多元音乐文化', dependency: '尊重' },
        { word1: '第三学段学生', word2: '音乐与姊妹艺术、其他学科，以及个人、自然、生活、社会、科技的广泛联系', dependency: '理解' },
        { word1: '第三学段学生', word2: '个人、自然、生活、社会、科技', dependency: '联系' },
        { word1: '第三学段学生', word2: '自己的想法', dependency: '有' },
        { word1: '第三学段学生', word2: '造型元素、形式原理和欣赏方法', dependency: '运用' },
        { word1: '第三学段学生', word2: '世界不同国家和地区的美术作品', dependency: '欣赏' },
        { word1: '第三学段学生', word2: '世界不同国家和地区的美术作品', dependency: '评述' },
        { word1: '第三学段学生', word2: '世界美术的多样性和差异性', dependency: '领略' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '养成' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '尊 重' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '理解' },
        { word1: '第三学段学生', word2: '传统与现代的工具、材料和媒介，以及习得的美术知 识、技能和思维方式', dependency: '运用' },
        { word1: '第三学段学生', word2: '美术知 识、技能和思维方式', dependency: '习得' },
        { word1: '第三学段学生', word2: '平面、立体或动态等表现形式的美术作 品', dependency: '创作' },
        { word1: '第三学段学生', word2: '创意表达能力', dependency: '提升' },
        { word1: '第三学段学生', word2: '创意', dependency: '表达' },
        { word1: '第三学段学生', word2: '环境规划', dependency: '进行' },
        { word1: '第三学段学生', word2: '环境', dependency: '规划' },
        { word1: '第三学段学生', word2: '社会责任意识', dependency: '增强' },
        { word1: '第三学段学生', word2: '不同的工具和材料', dependency: '利用' },
        { word1: '第三学段学生', word2: '工艺品', dependency: '制作' },
        { word1: '第三学段学生', word2: '工艺品', dependency: '创作' },
        { word1: '第三学段学生', word2: '传统工艺“守正创新"的内涵与意义', dependency: '体会' },
        { word1: '第三学段学生', word2: '正', dependency: '守' },
        { word1: '第三学段学生', word2: '校园现实生活', dependency: '结合' },
        { word1: '第三学段学生', word2: '校园微电影', dependency: '创编' },
        { word1: '第三学段学生', word2: '综合探索与学习迁移的能力', dependency: '增强' },
        { word1: '第三学段学生', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第四学段学生', word2: '音乐的思想感情和内涵意蕴', dependency: '把握' },
        { word1: '第四学段学生', word2: '作品中蕴含的爱国主义、集体主义', dependency: '理解' },
        { word1: '第四学段学生', word2: '民族精神、时代精神等', dependency: '体悟' },
        { word1: '第四学段学生', word2: '国家认同 感、归属感、责任感和使命感', dependency: '增强' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '感知' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '体验' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '理解' },
        { word1: '第四学段学生', word2: '不同音乐表现特征的差异与联系', dependency: '辨识' },
        { word1: '第四学段学生', word2: '音乐', dependency: '表现' },
        { word1: '第四学段学生', word2: '初步的音 乐欣赏与评述能力', dependency: '具有' },
        { word1: '第四学段学生', word2: '音 乐', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '音 乐', dependency: '评述' },
        { word1: '第四学段学生', word2: '对音乐的浓厚兴趣', dependency: '保持' },
        { word1: '第四学段学生', word2: '积极乐观的态度', dependency: '养成' },
        { word1: '第四学段学生', word2: '音乐表现活动', dependency: '参与' },
        { word1: '第四学段学生', word2: '音乐', dependency: '活动' },
        { word1: '第四学段学生', word2: '富有个性和创意的二度创作及表现形式的创新', dependency: '进行' },
        { word1: '第四学段学生', word2: '表现形式', dependency: '创新' },
        { word1: '第四学段学生', word2: '创意实践能力和艺术表现水平', dependency: '提高' },
        { word1: '第四学段学生', word2: '创意', dependency: '实践' },
        { word1: '第四学段学生', word2: '创意', dependency: '表现' },
        { word1: '第四学段学生', word2: '自信心', dependency: '增强' },
        { word1: '第四学段学生', word2: '自主学习能力和团队合作能力', dependency: '发展' },
        { word1: '第四学段学生', word2: '自主学习能力和团队合作能力', dependency: '学习' },
        { word1: '第四学段学生', word2: '比较完整的短小音乐作品', dependency: '编创' },
        { word1: '第四学段学生', word2: '比较完整的短小音乐作品', dependency: '展示' },
        { word1: '第四学段学生', word2: '自己的想法和情 感', dependency: '表达' },
        { word1: '第四学段学生', word2: '较丰富的想象力和创造力', dependency: '具有' },
        { word1: '第四学段学生', word2: '想象力和创造力', dependency: '丰富' },
        { word1: '第四学段学生', word2: '中国音乐文化', dependency: '热爱' },
        { word1: '第四学段学生', word2: '民族文化智慧', dependency: '汲取' },
        { word1: '第四学段学生', word2: '文化自 信', dependency: '坚定' },
        { word1: '第四学段学生', word2: '世界音乐文化的多样性', dependency: '领略' },
        { word1: '第四学段学生', word2: '不同音乐的表达方式', dependency: '包容' },
        { word1: '第四学段学生', word2: '文 化差异', dependency: '尊重' },
        { word1: '第四学段学生', word2: '不同艺术的主要表现形式、表现手段和审美特征', dependency: '认识' },
        { word1: '第四学段学生', word2: '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用', dependency: '理解' },
        { word1: '第四学段学生', word2: '美术产生的背景及不同时代、地区、民族和国家的美术特 征', dependency: '了解' },
        { word1: '第四学段学生', word2: '美术产生的背景及不同时代、地区、民族和国家的美术特 征', dependency: '产生' },
        { word1: '第四学段学生', word2: '开放包容的心态和人类命运共同体意识', dependency: '知道' },
        { word1: '第四学段学生', word2: '中华民族追求独立解放和党团结带领人民进行革命、建设、改革', dependency: '作品反映' },
        { word1: '第四学段学生', word2: '人民进行革命、建设、改革', dependency: '带领' },
        { word1: '第四学段学生', word2: '对伟 大祖国、中华民族的情感', dependency: '增强' },
        { word1: '第四学段学生', word2: '红色基因', dependency: '传承' },
        { word1: '第四学段学生', word2: '文化自信', dependency: '坚定' },
        { word1: '第四学段学生', word2: '文化自信', dependency: '形成' },
        { word1: '第四学段学生', word2: '平面、立体或动态等表现形式的美术作品', dependency: '创作' },
        { word1: '第四学段学生', word2: '对自然与社会的感受、思考和认识', dependency: '达' },
        { word1: '第四学段学生', word2: '创造性思维能力', dependency: '发展' },
        { word1: '第四学段学生', word2: '“设计满足实用功能与审美价值，传递社会责任”的设计原则', dependency: '了解' },
        { word1: '第四学段学生', word2: '实用功能与审美价值', dependency: '满足' },
        { word1: '第四学段学生', word2: '社会责任', dependency: '传递' },
        { word1: '第四学段学生', word2: '社会责任', dependency: '学习' },
        { word1: '第四学段学生', word2: '社会责任', dependency: '需求' },
        { word1: '第四学段学生', word2: '作品', dependency: '设计' },
        { word1: '第四学段学生', word2: '社会责任感', dependency: '增强' },
        { word1: '第四学段学生', word2: '非物质文化遗产的含义', dependency: '了解' },
        { word1: '第四学段学生', word2: '传统工艺品或文创产品', dependency: '制作' },
        { word1: '第四学段学生', word2: '继承与发展文化遗产是我们的责任', dependency: '认 识' },
        { word1: '第四学段学生', word2: '文化遗产', dependency: '继承' },
        { word1: '第四学段学生', word2: '文化遗产', dependency: '发展' },
        { word1: '第四学段学生', word2: '美术对个人发展、社会进步及构建人类命运共同体具有独 特的作用', dependency: '理解' },
        { word1: '第四学段学生', word2: '个人', dependency: '发展' },
        { word1: '第四学段学生', word2: '人类命运共同体', dependency: '构建' },
        { word1: '第四学段学生', word2: '独 特的作用', dependency: '具有' },
        { word1: '第四学段学生', word2: '综合探索与学习迁移的能力', dependency: '提升' },
        { word1: '第四学段学生', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第四学段学生', word2: '不同体裁和风格的舞蹈', dependency: '了解' },
        { word1: '第四学段学生', word2: '舞蹈美的丰富性', dependency: '感受' },
        { word1: '第四学段学生', word2: '不同舞种的舞蹈姿态与基本动作', dependency: '掌握' },
        { word1: '第四学段学生', word2: '身体语言', dependency: '运用' },
        { word1: '第四学段学生', word2: '创意', dependency: '有' },
        { word1: '第四学段学生', word2: '不同体裁和风格的舞蹈', dependency: '表现' },
        { word1: '第四学段学生', word2: '艺术表现能力', dependency: '提升' },
        { word1: '第四学段学生', word2: '中外舞蹈艺术特色', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '中外舞蹈艺术特色', dependency: '分析' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化的学习与传承', dependency: '加强' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化', dependency: '学习' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化', dependency: '传承' },
        { word1: '第四学段学生', word2: '多种艺术表现形式', dependency: '运用' },
        { word1: '第四学段学生', word2: '多种艺术表现形式', dependency: '合作' },
        { word1: '第四学段学生', word2: '情感、观念和想象', dependency: '表达' },
        { word1: '第四学段学生', word2: '舞蹈', dependency: '编排' },
        { word1: '第四学段学生', word2: '舞蹈', dependency: '实践' },
        { word1: '第四学段学生', word2: '创新思维能力', dependency: '提升' },
        { word1: '第四学段学生', word2: '戏剧编演的方法', dependency: '了解' },
        { word1: '第四学段学生', word2: '戏剧', dependency: '编演' },
        { word1: '第四学段学生', word2: '运用多种艺术手段进行戏剧演出的基本能力', dependency: '具有' },
        { word1: '第四学段学生', word2: '多种艺术手段', dependency: '运用' },
        { word1: '第四学段学生', word2: '戏剧演出', dependency: '进行' },
        { word1: '第四学段学生', word2: '戏剧', dependency: '演出' },
        { word1: '第四学段学生', word2: '戏曲', dependency: '含' },
        { word1: '第四学段学生', word2: '初步欣赏和分析', dependency: '进行' },
        { word1: '第四学段学生', word2: '对戏剧（含戏曲）艺术作品', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '对戏剧（含戏曲）艺术作品', dependency: '分析' },
        { word1: '第四学段学生', word2: '初步表达观剧感受和见解的能力', dependency: '具有' },
        { word1: '第四学段学生', word2: '观剧感受和见解', dependency: '表达' },
        { word1: '第四学段学生', word2: '剧', dependency: '观' },
        { word1: '第四学段学生', word2: '第四学段学生', dependency: '形成' },
        { word1: '第四学段学生', word2: '“教育戏剧”“教育剧场”的方法', dependency: '了解' },
        { word1: '第四学段学生', word2: '一定的戏剧应 用活动', dependency: '进行' },
        { word1: '第四学段学生', word2: '一定的戏剧应 用活动', dependency: '活动' },
        { word1: '第四学段学生', word2: '中外戏剧艺术史的基本常识', dependency: '掌握' },
        { word1: '第四学段学生', word2: '中外戏剧艺术的不 同文化背景', dependency: '认识' },
        { word1: '第四学段学生', word2: '中国戏曲艺术所具有的独特的审美特征', dependency: '了解' },
        { word1: '第四学段学生', word2: '中国戏曲艺术审美特征', dependency: '具有' },
        { word1: '第四学段学生', word2: '文化自信', dependency: '坚 定' },
        { word1: '第四学段学生', word2: '戏剧（含戏曲）活动', dependency: '参与' },
        { word1: '第四学段学生', word2: '戏曲', dependency: '活动' },
        { word1: '第四学段学生', word2: '与同伴合作的意识和团队精神', dependency: '养成' },
        { word1: '第四学段学生', word2: '与同伴合作的意识和团队精神', dependency: '合作' },
        { word1: '第四学段学生', word2: '脚本', dependency: '创编' },
        { word1: '第四学段学生', word2: '剧目', dependency: '演出' },
        { word1: '第四学段学生', word2: '对他人及自我的理解', dependency: '增进' },
        { word1: '第四学段学生', word2: '对他人及自我', dependency: '理解' },
        { word1: '第四学段学生', word2: '身心健康成长', dependency: '促进' },
        { word1: '第四学段学生', word2: '身心健康成长', dependency: '成长' },
        { word1: '第四学段学生', word2: '身心健康成长', dependency: '活动' },
        { word1: '第四学段学生', word2: '社会主义核心价值观', dependency: '树立' },
        { word1: '第四学段学生', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '传承' },
        { word1: '第四学段学生', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '弘扬' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）与真实世界、虚拟世界的联系', dependency: '建立' },
        { word1: '第四学段学生', word2: '数字媒体艺术', dependency: '含' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）与真实世界、虚拟世界', dependency: '联系' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的形态特征', dependency: '把握' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）的基本创作技巧和艺术语言', dependency: '掌握' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）', dependency: '创作' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的制作流程', dependency: '了解' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品', dependency: '制作' },
        { word1: '第四学段学生', word2: '简单的数字设备和软件', dependency: '运用' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品', dependency: '创作' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的主要类型、风格与流派', dependency: '了解' },
        { word1: '第四学段学生', word2: '简单评述', dependency: '进行' },
        { word1: '第四学段学生', word2: '对影视（含数字媒体艺术）作品', dependency: '评述' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）在传承和弘扬中华优秀传统文化、革命文化、社会主义先 进文化，感悟伟大建党精神过程中的重要作用', dependency: '认识' },
        { word1: '第四学段学生', word2: '伟大建党精神', dependency: '感悟' },
        { word1: '第四学段学生', word2: '其他艺术学科，以及信息科技等课程', dependency: '学习' },
        { word1: '第四学段学生', word2: '学科，以及信息科技等课程的学习', dependency: '结合' },
        { word1: '第四学段学生', word2: '综合融通', dependency: '进行' },
        { word1: '第四学段学生', word2: '影视艺术思维、数字媒体思维、信息思维和科技思维等', dependency: '综合' },
        { word1: '第四学段学生', word2: '影视艺术思维、数字媒体思维、信息思维和科技思维等', dependency: '融通' },
        { word1: '第四学段学生', word2: '创意活动', dependency: '开展' },
        { word1: '第四学段学生', word2: '审美和人文素养', dependency: '提升' },
        { word1: '艺术', word2: '第一学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第二学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第三学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第四学段学生', dependency: '阶段' },
      ],
    }
  },
}
</script>

<style></style>
