<template>
  <div>
    <knowledge-graph :word="word" :relationship="relationship" :subjectName="subjectName"></knowledge-graph>
  </div>
</template>

<script>
import knowledgeGraph from '@/components/works/knowledgeGraph'
export default {
  components: { knowledgeGraph },
  data() {
    return {
      subjectName: '信息技术',
      word: [
        '数字设备对社会发展和人们生活的影响',
        '利用信息科技',
        '自主学习和合作学习',
        '该过程',
        '网络中信息编码、传输和呈现的原理',
        '科技活动中',
        '用户标识、密码和身份验证等措施',
        '信息备份',
        '信息真伪',
        '数字身份的唯一性与信用价值',
        '信息社会',
        '项目活动',
        '对数字设备',
        '自主可控技术对保障网络安全和数据安全的重要性',
        '整体问题解决',
        '同类问题',
        '网盘',
        '多种方法',
        '对事物',
        '使用数字设备解决问题的过程',
        '过程与控制',
        '开展数字化创新活动，感受用信息科技表达观点',
        '应用信息科技',
        '学习与生活',
        '第三学段（计算思维）学生',
        '人工智能带来的伦理与安全挑战',
        '简单的多媒体作品创作、展示、交流',
        '线上线下学习方式的异同',
        '给人们的学习、生活和工作方式',
        '解决问题的需求和数据源',
        '他人数字作品',
        '网络安全和数据安全',
        '个人在线学习资源',
        '在线学习环境',
        '互联网对社会各领域的影响',
        '操作步骤',
        '系统',
        '数字设备及数字资源',
        '信息科技领域的伦理道德规范',
        '与他人分享信息',
        '表达',
        '互联网和物联网',
        '顺序、分支、循环三种基本控制结构',
        '知识产权',
        '对重要信息',
        '数字化学习与创新学段目标）学生',
        '人工智能',
        '文字、图片和声音',
        '对信息科技的求知欲',
        '行为规范',
        '主动使用数字设备的兴趣与意识',
        '家长和教师',
        '数据编码的作用与意义',
        '信息体验信息存储和传输过程中所必需的编码及解码步骤',
        '数据编码',
        '可解决的小问题',
        '反馈对系统优化的作用',
        '教师',
        '与他人',
        '算法的特征和效率',
        '编码及解码步骤',
        '用不同方法解决同一问题时可能存在时间效率上的差别',
        '第四学段（信息社会责任学段目标）学生',
        '人们',
        '用计算机实现过程与控制的方案并在实验系统中通过编程等手段',
        '第二学段（信息社会责任学段目标）学生',
        '数据之间的关系',
        '自身',
        '算法的优势及对知识产权保护的作用',
        '互动',
        '信息',
        '第四学段（数字化学习与创新学段目标）学生',
        '物理世界与数字世界',
        '数字设备的使用时间',
        '可处理的子问题',
        '数字设备使用的基本规范',
        '网络信息交流',
        '任务',
        '第一学段（信息社会责任学段目标）学生',
        '自身学习、生活',
        '学习方法',
        '用信息科技表达观点',
        '保护个人隐私的意识',
        '科技活动中应遵循的价值观念、道德责任和行为准则',
        '自主动手解决问题、掌握核心技术的意识',
        '自我管理能力',
        '理由',
        '自己在学习与生活中发生的事情',
        '在线平台和工具',
        '数字设备',
        '学习质量',
        '算法',
        '多媒体作品',
        '第三学段（数字化学习与创新学段目标）学生',
        '数据安全',
        '加密',
        '威胁数据安全的因素',
        '真实与虚假之分',
        '防护措施',
        '伦理与安全挑战',
        '核心技术',
        '第四学段（计算思维）学生',
        '案例',
        '用不同方法解决同一问题',
        '其中数据处理和应用的方法与过程',
        '第二学段（数字化学习与创新学段目标）学生',
        '对社会各领域',
        '原始创新对国家可持续发展的重要性',
        '信息科技支持学习的新方法、新模式',
        '评论',
        '国家',
        '第三学段（信息社会责任学段目标）学生',
        '问题解决的需要',
        '合作学习',
        '第四学段（信息意识）学生',
        '科学基础',
        '数字作品所有者的权益',
        '个人隐私',
        '数字化创新活动',
        '文字、图符、语音等多种输入方式的表达与交流效果',
        '个人见闻和想法',
        '第三学段（信息意识）学生',
        '其',
        '事情',
        '作品',
        '对个人日常学习与生活',
        '同一问题',
        '文字、图符、语音等',
        '崇尚科学精神、原创精神',
        '整体问题',
        '生活中的过程与控制场景',
        '用户',
        '数字身份对个人日常学习与生活的作用和意义',
        '方案',
        '身边的算法',
        '的物联系统原型',
        '算法的特征',
        '在线平台对学习的影响，比较线上线下学习方式的异同',
        '数据编码是保持信息社会组织与秩序的科学基础',
        '信息科技',
        '信息的多种表示方式',
        '合适的数字设备',
        '完善和迭代',
        '第二学段（计算思维）学生',
        '第二学段（信息意识）学生',
        '信息技术',
        '个人',
        '一系列的实施步骤',
        '加密软件',
        '问题',
        '学习活动',
        '生活和学习中的问题',
        '实施过程',
        '来源',
        '社会',
        '使用人工智能和不使用人工智能处理同类问题效果的异同',
        '互联网交互方式',
        '互联网和物联网给人们的学习、生活和工作方式带来的改变',
        '软件系统',
        '人工智能对信息社会发展的作用',
        '与人工智能',
        '人工智能应用场景',
        '使用数字设备及数字资源开展学习活动',
        '学习手段',
        '伙伴',
        '网络平台中的技术工具、软件系统的功能与应用',
        '信息技术工具',
        '数据安全意识',
        '数据',
        '任务实施的主要步骤',
        '简单的物联系统原型',
        '利用信息科技进行自主学习和合作学习的能力',
        '算法对解决生活和学习中的问题的重要性',
        '数字作品',
        '解决同一问题可能会有多种方法',
        '观点',
        '对信息科技的好奇心和学习兴趣',
        '学习资源',
        '恰当的数字设备',
        '第一学段（计算思维）学生',
        '因素',
        '个人日常',
        '信息有真实与虚假之分',
        '应用信息科技获取与处理信息的优势',
        '学习方式',
        '数据的作用与价值',
        '学生',
        '价值观念、道德责任和行为准则',
        '自主可控对国家安全以及互联网和物联网未来发展的重要意义',
        '所需学习资源',
        '恰当的数字化方式',
        '第一学段（数字化学习与创新学段目标）学生',
        '解决同一问题',
        '对学习作品',
        '创新实践活动',
        '保持信息社会组织与秩序的科学基础',
        '社会公共秩序',
        '相关的法律法规',
        '创作步骤',
        '数据安全防护的常用方法和策略',
        '第一学段（信息意识）学生',
        '改变',
        '数字设备使用的好习惯',
        '提取',
        '简单的数字作品',
        '他人隐私',
        '时间效率上的差别',
        '在线平台',
        '安全',
        '互联网',
        '结果',
        '互联网知识',
        '信息社会组织与秩序',
        '科学精神、原创精神',
        '学习',
        '物理世界与数字世界深度融合的环境',
        '网络信息',
        '记录结果',
        '自我判断意识和责任感',
        '安全防护',
        '身份',
        '将创新理念融入自身学习、生活的意识',
        '意识',
      ],
      relationship: [
        { word1: '信息技术', word2: '第一学段（信息意识）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第二学段（信息意识）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第三学段（信息意识）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第四学段（信息意识）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第一学段（计算思维）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第二学段（计算思维）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第三学段（计算思维）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第四学段（计算思维）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第一学段（数字化学习与创新学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第二学段（数字化学习与创新学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第三学段（数字化学习与创新学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第四学段（数字化学习与创新学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第一学段（信息社会责任学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第二学段（信息社会责任学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第三学段（信息社会责任学段目标）学生', dependency: '阶段' },
        { word1: '信息技术', word2: '第四学段（信息社会责任学段目标）学生', dependency: '阶段' },
        { word1: '第一学段（信息意识）学生', word2: '主动使用数字设备的兴趣与意识', dependency: '有' },
        { word1: '第一学段（信息意识）学生', word2: '数字设备', dependency: '使用' },
        { word1: '第一学段（信息意识）学生', word2: '数字设备使用的基本规范', dependency: '知道' },
        { word1: '第一学段（信息意识）学生', word2: '数字设备的使用时间', dependency: '安排' },
        { word1: '第一学段（信息意识）学生', word2: '数字设备使用的好习惯', dependency: '养成' },
        { word1: '学生', word2: '文字、图符、语音等多种输入方式的表达与交流效果', dependency: '体验' },
        { word1: '学生', word2: '文字、图符、语音等', dependency: '表达' },
        { word1: '学生', word2: '意识', dependency: '有' },
        { word1: '学生', word2: '数字设备', dependency: '使用' },
        { word1: '学生', word2: '文字、图片和声音', dependency: '处理' },
        { word1: '第一学段（信息意识）学生', word2: '信息有真实与虚假之分', dependency: '知道' },
        { word1: '信息', word2: '真实与虚假之分', dependency: '有' },
        { word1: '信息', word2: '恰当的数字化方式', dependency: '选用' },
        { word1: '信息', word2: '个人见闻和想法', dependency: '表达' },
        { word1: '信息', word2: '与他人分享信息', dependency: '乐于' },
        { word1: '与他人', word2: '信息', dependency: '分享' },
        { word1: '第二学段（信息意识）学生', word2: '数据的作用与价值', dependency: '了解' },
        { word1: '第二学段（信息意识）学生', word2: '数字设备对社会发展和人们生活的影响', dependency: '列举' },
        { word1: '第二学段（信息意识）学生', word2: '个人日常', dependency: '发展' },
        { word1: '个人', word2: '个人日常', dependency: '生活' },
        { word1: '数字设备', word2: '对个人日常学习与生活', dependency: '影响' },
        { word1: '第二学段（信息意识）学生', word2: '数据编码的作用与意义', dependency: '知道' },
        { word1: '学生', word2: '数据编码是保持信息社会组织与秩序的科学基础', dependency: '理解' },
        { word1: '数据编码', word2: '保持信息社会组织与秩序的科学基础', dependency: '是' },
        { word1: '科学基础', word2: '信息社会组织与秩序', dependency: '保持' },
        { word1: '科学基础', word2: '信息社会', dependency: '组织' },
        { word1: '科学基础', word2: '信息社会', dependency: '使用' },
        { word1: '学生', word2: '数字身份对个人日常学习与生活的作用和意义', dependency: '知道' },
        { word1: '个人', word2: '数字身份对个人日常学习与生活的作用和意义', dependency: '学习' },
        { word1: '个人', word2: '数字身份对个人日常学习与生活的作用和意义', dependency: '生活' },
        { word1: '第二学段（信息意识）学生', word2: '网络信息交流', dependency: '进行' },
        { word1: '第二学段（信息意识）学生', word2: '网络信息', dependency: '交流' },
        { word1: '第三学段（信息意识）学生', word2: '物理世界与数字世界深度融合的环境', dependency: '体验' },
        { word1: '第三学段（信息意识）学生', word2: '物理世界与数字世界', dependency: '融合' },
        { word1: '第三学段（信息意识）学生', word2: '应用信息科技获取与处理信息的优势', dependency: '感受' },
        { word1: '第三学段（信息意识）学生', word2: '信息科技', dependency: '应用' },
        { word1: '应用信息科技', word2: '信息', dependency: '获取' },
        { word1: '应用信息科技', word2: '信息', dependency: '处理' },
        { word1: '应用信息科技', word2: '意识', dependency: '有' },
        { word1: '第三学段（信息意识）学生', word2: '信息技术工具', dependency: '选用' },
        { word1: '第三学段（信息意识）学生', word2: '信息', dependency: '处理' },
        { word1: '第三学段（信息意识）学生', word2: '科学精神、原创精神', dependency: '崇尚' },
        { word1: '崇尚科学精神、原创精神', word2: '将创新理念融入自身学习、生活的意识', dependency: '具有' },
        { word1: '崇尚科学精神、原创精神', word2: '自身学习、生活', dependency: '融入' },
        { word1: '自身', word2: '自身学习、生活', dependency: '学习' },
        { word1: '自身', word2: '自身学习、生活', dependency: '生活' },
        { word1: '自身', word2: '解决问题的需求和数据源', dependency: '确定' },
        { word1: '自身', word2: '问题', dependency: '解决' },
        { word1: '自身', word2: '问题', dependency: '获取' },
        { word1: '自身', word2: '数据', dependency: '筛选' },
        { word1: '自身', word2: '数据', dependency: '分析' },
        { word1: '第四学段（信息意识）学生', word2: '问题', dependency: '观察' },
        { word1: '第四学段（信息意识）学生', word2: '互联网对社会各领域的影响', dependency: '探究' },
        { word1: '学生', word2: '互联网对社会各领域的影响', dependency: '理解' },
        { word1: '互联网', word2: '对社会各领域', dependency: '影响' },
        { word1: '学生', word2: '互联网交互方式', dependency: '体验' },
        { word1: '学生', word2: '互联网交互方式', dependency: '交互' },
        { word1: '学生', word2: '互联网和物联网给人们的学习、生活和工作方式带来的改变', dependency: '感受' },
        { word1: '人们', word2: '互联网和物联网给人们的学习、生活和工作方式带来的改变', dependency: '学习' },
        { word1: '人们', word2: '互联网和物联网给人们的学习、生活和工作方式带来的改变', dependency: '工作' },
        { word1: '互联网和物联网', word2: '改变', dependency: '带来' },
        { word1: '互联网和物联网', word2: '给人们的学习、生活和工作方式', dependency: '改变' },
        { word1: '学生', word2: '人工智能对信息社会发展的作用', dependency: '了解' },
        { word1: '学生', word2: '信息社会', dependency: '发展' },
        { word1: '学生', word2: '自主动手解决问题、掌握核心技术的意识', dependency: '具有' },
        { word1: '学生', word2: '自主动手解决问题、掌握核心技术的意识', dependency: '动手' },
        { word1: '学生', word2: '问题', dependency: '解决' },
        { word1: '学生', word2: '核心技术', dependency: '掌握' },
        { word1: '学生', word2: '互联网知识', dependency: '学习' },
        { word1: '学生', word2: '数据安全意识', dependency: '增强' },
        { word1: '学生', word2: '安全防护', dependency: '进行' },
        { word1: '学生', word2: '安全防护', dependency: '防护' },
        { word1: '第一学段（计算思维）学生', word2: '安全防护', dependency: '要求' },
        { word1: '数字设备', word2: '安全防护', dependency: '指导' },
        { word1: '数字设备', word2: '使用数字设备解决问题的过程', dependency: '体验' },
        { word1: '数字设备', word2: '数字设备', dependency: '使用' },
        { word1: '数字设备', word2: '问题', dependency: '解决' },
        { word1: '数字设备', word2: '信息的多种表示方式', dependency: '知道' },
        { word1: '数字设备', word2: '信息', dependency: '表示' },
        { word1: '数字设备', word2: '任务', dependency: '给定' },
        { word1: '数字设备', word2: '任务实施的主要步骤', dependency: '识别' },
        { word1: '数字设备', word2: '任务', dependency: '实施' },
        { word1: '数字设备', word2: '表达', dependency: '进行' },
        { word1: '数字设备', word2: '表达', dependency: '表达' },
        { word1: '数字设备', word2: '操作步骤', dependency: '说出' },
        { word1: '学生', word2: '合适的数字设备', dependency: '选用' },
        { word1: '数字设备', word2: '合适的数字设备', dependency: '合适' },
        { word1: '第二学段（计算思维）学生', word2: '理由', dependency: '解决' },
        { word1: '第二学段（计算思维）学生', word2: '理由', dependency: '说明' },
        { word1: '第二学段（计算思维）学生', word2: '对事物', dependency: '理解' },
        { word1: '第二学段（计算思维）学生', word2: '信息体验信息存储和传输过程中所必需的编码及解码步骤', dependency: '表达' },
        { word1: '第二学段（计算思维）学生', word2: '信息', dependency: '交流' },
        { word1: '学生', word2: '信息', dependency: '体验' },
        { word1: '学生', word2: '编码及解码步骤', dependency: '必需' },
        { word1: '学生', word2: '问题', dependency: '划分' },
        { word1: '学生', word2: '可解决的小问题', dependency: '为' },
        { word1: '第二学段（计算思维）学生', word2: '整体问题解决', dependency: '实现' },
        { word1: '第二学段（计算思维）学生', word2: '整体问题', dependency: '解决' },
        { word1: '第二学段（计算思维）学生', word2: '问题解决的需要', dependency: '依据' },
        { word1: '第二学段（计算思维）学生', word2: '问题', dependency: '解决' },
        { word1: '第二学段（计算思维）学生', word2: '数据', dependency: '组织' },
        { word1: '第二学段（计算思维）学生', word2: '数据', dependency: '分析' },
        { word1: '第二学段（计算思维）学生', word2: '数据之间的关系', dependency: '呈现' },
        { word1: '第二学段（计算思维）学生', word2: '数据之间的关系', dependency: '支撑' },
        { word1: '第二学段（计算思维）学生', word2: '观点', dependency: '形成' },
        { word1: '第三学段（计算思维）学生', word2: '算法的特征和效率', dependency: '了解' },
        { word1: '第三学段（计算思维）学生', word2: '算法', dependency: '描述' },
        { word1: '学生', word2: '解决同一问题可能会有多种方法', dependency: '知道' },
        { word1: '学生', word2: '同一问题', dependency: '解决' },
        { word1: '解决同一问题', word2: '多种方法', dependency: '有' },
        { word1: '第三学段（计算思维）学生', word2: '用不同方法解决同一问题时可能存在时间效率上的差别', dependency: '认识' },
        { word1: '第三学段（计算思维）学生', word2: '同一问题', dependency: '解决' },
        { word1: '用不同方法解决同一问题', word2: '时间效率上的差别', dependency: '存在' },
        { word1: '用不同方法解决同一问题', word2: '任务', dependency: '给定' },
        { word1: '用不同方法解决同一问题', word2: '其', dependency: '分解' },
        { word1: '用不同方法解决同一问题', word2: '一系列的实施步骤', dependency: '为' },
        { word1: '用不同方法解决同一问题', word2: '顺序、分支、循环三种基本控制结构', dependency: '使用' },
        { word1: '用不同方法解决同一问题', word2: '实施过程', dependency: '描述' },
        { word1: '用不同方法解决同一问题', word2: '该过程', dependency: '验证' },
        { word1: '用不同方法解决同一问题', word2: '问题', dependency: '解决' },
        { word1: '用不同方法解决同一问题', word2: '问题', dependency: '分解' },
        { word1: '用不同方法解决同一问题', word2: '可处理的子问题', dependency: '为' },
        { word1: '用不同方法解决同一问题', word2: '问题', dependency: '处理' },
        { word1: '用不同方法解决同一问题', word2: '反馈对系统优化的作用', dependency: '了解' },
        { word1: '用不同方法解决同一问题', word2: '系统', dependency: '优化' },
        { word1: '第四学段（计算思维）学生', word2: '网络平台中的技术工具、软件系统的功能与应用', dependency: '熟悉' },
        { word1: '第四学段（计算思维）学生', word2: '软件系统', dependency: '应用' },
        { word1: '第四学段（计算思维）学生', word2: '简单的物联系统原型', dependency: '设计' },
        { word1: '第四学段（计算思维）学生', word2: '简单的物联系统原型', dependency: '搭建' },
        { word1: '的物联系统原型', word2: '简单的物联系统原型', dependency: '简单' },
        { word1: '的物联系统原型', word2: '其中数据处理和应用的方法与过程', dependency: '体验' },
        { word1: '的物联系统原型', word2: '数据', dependency: '处理' },
        { word1: '的物联系统原型', word2: '数据', dependency: '应用' },
        { word1: '的物联系统原型', word2: '网络中信息编码、传输和呈现的原理', dependency: '知道' },
        { word1: '的物联系统原型', word2: '信息', dependency: '编码' },
        { word1: '的物联系统原型', word2: '信息', dependency: '传输' },
        { word1: '的物联系统原型', word2: '信息', dependency: '呈现' },
        { word1: '的物联系统原型', word2: '项目活动', dependency: '结合' },
        { word1: '的物联系统原型', word2: '数据', dependency: '分析' },
        { word1: '数据', word2: '数据', dependency: '呈现' },
        { word1: '数据', word2: '案例', dependency: '分析' },
        { word1: '数据', word2: '人工智能', dependency: '理解' },
        { word1: '学习与生活', word2: '人工智能', dependency: '需要' },
        { word1: '学习与生活', word2: '人工智能', dependency: '选用' },
        { word1: '学习与生活', word2: '使用人工智能和不使用人工智能处理同类问题效果的异同', dependency: '比较' },
        { word1: '学习与生活', word2: '人工智能', dependency: '使用' },
        { word1: '学习与生活', word2: '同类问题', dependency: '处理' },
        { word1: '学习与生活', word2: '同类问题', dependency: '学习' },
        { word1: '教师', word2: '学生', dependency: '指导' },
        { word1: '学生', word2: '使用数字设备及数字资源开展学习活动', dependency: '尝试' },
        { word1: '学生', word2: '数字设备及数字资源', dependency: '使用' },
        { word1: '学生', word2: '学习活动', dependency: '开展' },
        { word1: '学生', word2: '学习活动', dependency: '活动' },
        { word1: '学生', word2: '学习手段', dependency: '丰富' },
        { word1: '第一学段（数字化学习与创新学段目标）学生', word2: '学习方法', dependency: '改进' },
        { word1: '学生', word2: '对数字设备', dependency: '使用' },
        { word1: '学生', word2: '对信息科技的好奇心和学习兴趣', dependency: '了解' },
        { word1: '学生', word2: '对信息科技的好奇心和学习兴趣', dependency: '激发' },
        { word1: '学生', word2: '对信息科技的求知欲', dependency: '产生' },
        { word1: '学生', word2: '数字设备', dependency: '利用' },
        { word1: '学生', word2: '自己在学习与生活中发生的事情', dependency: '记录' },
        { word1: '事情', word2: '自己在学习与生活中发生的事情', dependency: '发生' },
        { word1: '事情', word2: '结果', dependency: '记录' },
        { word1: '事情', word2: '记录结果', dependency: '分类' },
        { word1: '事情', word2: '记录结果', dependency: '保存' },
        { word1: '事情', word2: '提取', dependency: '进行' },
        { word1: '事情', word2: '简单的数字作品', dependency: '创建' },
        { word1: '数字作品', word2: '简单的数字作品', dependency: '简单' },
        { word1: '学生', word2: '学习资源', dependency: '利用' },
        { word1: '第二学段（数字化学习与创新学段目标）学生', word2: '学习资源', dependency: '获取' },
        { word1: '学生', word2: '合作学习', dependency: '开展' },
        { word1: '学生', word2: '合作学习', dependency: '学习' },
        { word1: '学生', word2: '在线平台对学习的影响，比较线上线下学习方式的异同', dependency: '认识' },
        { word1: '数字化学习与创新学段目标）学生', word2: '线上线下学习方式的异同', dependency: '比较' },
        { word1: '教师', word2: '线上线下学习方式的异同', dependency: '指导' },
        { word1: '学生', word2: '个人在线学习资源', dependency: '管理' },
        { word1: '学生', word2: '信息科技', dependency: '借助' },
        { word1: '学生', word2: '简单的多媒体作品创作、展示、交流', dependency: '进行' },
        { word1: '学生', word2: '多媒体作品', dependency: '展示' },
        { word1: '学生', word2: '多媒体作品', dependency: '交流' },
        { word1: '学生', word2: '开展数字化创新活动，感受用信息科技表达观点', dependency: '尝试' },
        { word1: '学生', word2: '数字化创新活动', dependency: '开展' },
        { word1: '学生', word2: '用信息科技表达观点', dependency: '感受' },
        { word1: '学生', word2: '观点', dependency: '表达' },
        { word1: '学生', word2: '作品', dependency: '创作' },
        { word1: '学生', word2: '身边的算法', dependency: '学习' },
        { word1: '第三学段（数字化学习与创新学段目标）学生', word2: '算法的特征', dependency: '体会' },
        { word1: '第三学段（数字化学习与创新学段目标）学生', word2: '意识', dependency: '有' },
        { word1: '第三学段（数字化学习与创新学段目标）学生', word2: '其', dependency: '应用于' },
        { word1: '数字化学习与创新学段目标）学生', word2: '在线学习环境', dependency: '适应' },
        { word1: '学生', word2: '在线平台和工具', dependency: '利用' },
        { word1: '学生', word2: '生活中的过程与控制场景', dependency: '寻找' },
        { word1: '学生', word2: '用计算机实现过程与控制的方案并在实验系统中通过编程等手段', dependency: '设计' },
        { word1: '学生', word2: '过程与控制', dependency: '实现' },
        { word1: '学生', word2: '过程与控制', dependency: '验证' },
        { word1: '学生', word2: '恰当的数字设备', dependency: '利用' },
        { word1: '数字设备', word2: '恰当的数字设备', dependency: '恰当' },
        { word1: '数字设备', word2: '方案', dependency: '规划' },
        { word1: '数字设备', word2: '创作步骤', dependency: '描述' },
        { word1: '数字设备', word2: '作品', dependency: '学习' },
        { word1: '数字设备', word2: '完善和迭代', dependency: '进行' },
        { word1: '数字设备', word2: '对学习作品', dependency: '完善' },
        { word1: '第四学段（数字化学习与创新学段目标）学生', word2: '所需学习资源', dependency: '搜索' },
        { word1: '学生', word2: '信息科技支持学习的新方法、新模式', dependency: '探究' },
        { word1: '信息科技', word2: '学习', dependency: '支持' },
        { word1: '数字化学习与创新学段目标）学生', word2: '信息科技', dependency: '借助' },
        { word1: '数字化学习与创新学段目标）学生', word2: '学习质量', dependency: '提高' },
        { word1: '学生', word2: '学习质量', dependency: '学习' },
        { word1: '学生', word2: '恰当的数字设备', dependency: '选择' },
        { word1: '数字设备', word2: '学习', dependency: '支持' },
        { word1: '学生', word2: '学习方式', dependency: '改变' },
        { word1: '学生', word2: '利用信息科技进行自主学习和合作学习的能力', dependency: '具备' },
        { word1: '学生', word2: '自主学习和合作学习', dependency: '进行' },
        { word1: '利用信息科技', word2: '自主学习和合作学习', dependency: '学习' },
        { word1: '学生', word2: '创新实践活动', dependency: '开展' },
        { word1: '数字设备', word2: '创新实践活动', dependency: '活动' },
        { word1: '任务', word2: '创新实践活动', dependency: '要求' },
        { word1: '任务', word2: '在线平台', dependency: '借助' },
        { word1: '伙伴', word2: '在线平台', dependency: '合作' },
        { word1: '伙伴', word2: '作品', dependency: '设计' },
        { word1: '伙伴', word2: '作品', dependency: '创作' },
        { word1: '伙伴', word2: '作品', dependency: '活动' },
        { word1: '伙伴', word2: '原始创新对国家可持续发展的重要性', dependency: '认识' },
        { word1: '伙伴', word2: '原始创新对国家可持续发展的重要性', dependency: '创新' },
        { word1: '国家', word2: '原始创新对国家可持续发展的重要性', dependency: '发展' },
        { word1: '第一学段（信息社会责任学段目标）学生', word2: '个人隐私', dependency: '保护' },
        { word1: '家长和教师', word2: '学生', dependency: '帮助' },
        { word1: '学生', word2: '信息真伪', dependency: '确定' },
        { word1: '学生', word2: '他人数字作品', dependency: '浏览' },
        { word1: '学生', word2: '评论', dependency: '发表' },
        { word1: '学生', word2: '他人数字作品', dependency: '分享' },
        { word1: '学生', word2: '来源', dependency: '标注' },
        { word1: '学生', word2: '数字作品所有者的权益', dependency: '尊重' },
        { word1: '学生', word2: '社会公共秩序', dependency: '维护' },
        { word1: '学生', word2: '数字身份的唯一性与信用价值', dependency: '认识' },
        { word1: '学生', word2: '保护个人隐私的意识', dependency: '增强' },
        { word1: '学生', word2: '个人隐私', dependency: '保护' },
        { word1: '学生', word2: '自我管理能力', dependency: '提升' },
        { word1: '学生', word2: '第二学段（信息社会责任学段目标）学生', dependency: '形成' },
        { word1: '学生', word2: '第二学段（信息社会责任学段目标）学生', dependency: '生存' },
        { word1: '学生', word2: '威胁数据安全的因素', dependency: '了解' },
        { word1: '因素', word2: '数据安全', dependency: '威胁' },
        { word1: '防护措施', word2: '数据安全', dependency: '常见' },
        { word1: '学生', word2: '数据', dependency: '保护' },
        { word1: '社会', word2: '行为规范', dependency: '公认' },
        { word1: '学生', word2: '行为规范', dependency: '进行' },
        { word1: '学生', word2: '相关的法律法规', dependency: '遵守' },
        { word1: '第三学段（信息社会责任学段目标）学生', word2: '算法的优势及对知识产权保护的作用', dependency: '了解' },
        { word1: '第三学段（信息社会责任学段目标）学生', word2: '知识产权', dependency: '保护' },
        { word1: '学生', word2: '算法对解决生活和学习中的问题的重要性', dependency: '认识' },
        { word1: '学生', word2: '生活和学习中的问题', dependency: '解决' },
        { word1: '第三学段（信息社会责任学段目标）学生', word2: '自主可控技术对保障网络安全和数据安全的重要性', dependency: '认识' },
        { word1: '第三学段（信息社会责任学段目标）学生', word2: '网络安全和数据安全', dependency: '保障' },
        { word1: '第三学段（信息社会责任学段目标）学生', word2: '互联网', dependency: '应用' },
        { word1: '学生', word2: '用户标识、密码和身份验证等措施', dependency: '利用' },
        { word1: '学生', word2: '用户', dependency: '标识' },
        { word1: '学生', word2: '身份', dependency: '验证' },
        { word1: '学生', word2: '加密', dependency: '做好' },
        { word1: '学生', word2: '安全', dependency: '防护' },
        { word1: '学生', word2: '加密软件', dependency: '使用' },
        { word1: '学生', word2: '加密', dependency: '进行' },
        { word1: '学生', word2: '对重要信息', dependency: '加密' },
        { word1: '学生', word2: '网盘', dependency: '使用' },
        { word1: '学生', word2: '信息备份', dependency: '进行' },
        { word1: '学生', word2: '信息', dependency: '备份' },
        { word1: '学生', word2: '数据安全防护的常用方法和策略', dependency: '知道' },
        { word1: '学生', word2: '他人隐私', dependency: '尊重' },
        { word1: '学生', word2: '自主可控对国家安全以及互联网和物联网未来发展的重要意义', dependency: '了解' },
        { word1: '学生', word2: '互联网和物联网', dependency: '发展' },
        { word1: '学生', word2: '人工智能应用场景', dependency: '体验' },
        { word1: '学生', word2: '人工智能带来的伦理与安全挑战', dependency: '了解' },
        { word1: '人工智能', word2: '伦理与安全挑战', dependency: '带来' },
        { word1: '人工智能', word2: '伦理与安全挑战', dependency: '挑战' },
        { word1: '与人工智能', word2: '互动', dependency: '开展' },
        { word1: '与人工智能', word2: '自我判断意识和责任感', dependency: '增强' },
        { word1: '与人工智能', word2: '自我判断意识和责任感', dependency: '判断' },
        { word1: '与人工智能', word2: '信息科技领域的伦理道德规范', dependency: '遵循' },
        { word1: '与人工智能', word2: '科技活动中应遵循的价值观念、道德责任和行为准则', dependency: '明确' },
        { word1: '科技活动中', word2: '价值观念、道德责任和行为准则', dependency: '遵循' },
      ],
    }
  },
}
</script>

<style></style>
