<template>
  <div>
    <knowledge-graph :word="word" :relationship="relationship" :subjectName="subjectName"></knowledge-graph>
  </div>
</template>

<script>
import knowledgeGraph from '@/components/works/knowledgeGraph'
export default {
  components: { knowledgeGraph },
  data() {
    return {
      subjectName: '数学',
      word: [
        '建议',
        '自己的观点',
        '解决问题的方法和结论',
        '与数学',
        '信心',
        '自己能够学好数学，感受数学的价值，体验并欣赏数学美',
        '好奇心',
        '数学活动经验',
        '空间观念和几何直观',
        '平面图形的周长和面积的测量过程',
        '初步的数据意识',
        '货币单位、时间单位和基本方向',
        '数学问题',
        '数学在生活中的应用',
        '平均数的意义',
        '数学的作用',
        '万以内的数',
        '数学美',
        '长方形周长和面积',
        '平面直角坐标系',
        '物体长度的测量过程',
        '利用样本推断总体的过程',
        '在不同的情境中从数学的角度发现和提出问题',
        '序数',
        '质量单位',
        '量感、空间观念和几何直观',
        '数学活动中的成功',
        '数量关系',
        '理和表达数据的过程',
        '认识20以内的数，会20以内数的加减法（不含退位减法），能辨认物体和简单图形的形状，会简单的分类，解决日常生活中的简单问题',
        '题',
        '参与数学学习活动',
        '第二学段学生',
        '生活中的一些现象',
        '自然数的一些特征',
        '小数和分数的形成过程',
        '各种统计图表的功能',
        '小数和分数的意义',
        '数运算的一致性',
        '兴趣',
        '探索图形特征的过程',
        '退位减法',
        '从日常生活中发现和提出数学问题，探索分析和解决问题的方法',
        '推理能力',
        '简单的立体图形和平面图形',
        '第四学段学生',
        '简单的整数四则运算',
        '困难',
        '数与式的运算',
        '用数学方法解决问题',
        '理和表达数据的过程简单的判断',
        '社会生活中与数学相关的信息',
        '图形的平移、旋转和轴对称',
        '标准',
        '日常生活中的简单问题',
        '运算律',
        '初步的模型意识、几何直观和应用意识',
        '点的位置',
        '统计图表',
        '收集、整',
        '物体长度',
        '简单的数学问题',
        '他人的思考方法和结论',
        '简单的数学内容',
        '分析问题和解决问题的方法',
        '创造数学美',
        '几何直观、逻辑推理等方法',
        '有理数、实数',
        '物体和简单图形的形状',
        '成功的乐趣',
        '有理数、实数的形成过程',
        '基本的几何概念',
        '频数、频率和概率的意义',
        '第三学段学生',
        '运算结果的意义',
        '克服困难、解决问题的成就',
        '简单的分类过程',
        '对他人的想法提出建议',
        '在真实的情境中',
        '解决问题',
        '小数和分数',
        '平面图形的性质与关系',
        '分析问题和解决问题的基本方法',
        '时间单位和方向',
        '常见的平面图形',
        '所学的知识和方法',
        '基本的数量关系，以及几何直观、逻辑推理和其他学科的知识、方法',
        '学好数学的信心',
        '常见平面图形的周长和面积',
        '平均数、方差、四分位数等基本统计量',
        '好奇心和求知欲',
        '生活经验和幼儿园相关活动经验',
        '问题',
        '数学与生活密切联系',
        '简单的数的抽象过程',
        '常见立体图形的体积和表面积',
        '长方形周长和面积的计算方法',
        '现实问题中的数量关系和变化规律',
        '独立思考并与他人合作交流解决问题的过程',
        '运用基本的',
        '分类',
        '初步的量感和空间观念',
        '结果的合理性',
        '运算能力',
        '数学和其他学科知识与方法',
        '数学在实际生活中的应用',
        '随机现象',
        '自己的想法',
        '应用数学和其他学科知识与方法解决问题',
        '认真勤奋、独立思考、合作交流、反思质疑的学习习惯',
        '数据',
        '克服困难',
        '平移、旋转和轴对称的基本特征',
        '分析和解决问题的方法',
        '运用基本的数量关系，以及几何直观、逻辑推理和其他学科的知识、方法分析与解决问题，形成模型意识和初步的应用意识、创新意识',
        '较复杂的整数四则运算和简单的小数、分数的加减运算',
        '运用所学的知识和方法解决问题',
        '数据收集与整理的基本方法',
        '长方形和正方形的特征',
        '样本',
        '数',
        '总体',
        '图形特征',
        '随机现象发生的可能性',
        '第一学段学生',
        '日常生活中与数学相关的信息',
        '解决问题的思考过程',
        '基本的几何证明方法',
        '数学的价值',
        '数学',
        '小数和分数的四则运算',
        '数学与生活有密切联系',
        '20以内的数',
        '数学和其他学科的知识',
        '数据收集、整理和呈现的简单方法',
        '数学学习活动',
        '利用统计图表表示数据的方法',
        '几何图形面积和体积的计算方法',
        '简单的数据收集过程',
        '知识和方法',
        '认真勤奋、独立思考、合作交流、反思质疑的习惯',
        '他人的意见',
      ],
      relationship: [
        { word1: '第一学段学生', word2: '简单的数的抽象过程', dependency: '经历' },
        { word1: '第一学段学生', word2: '万以内的数', dependency: '认识' },
        { word1: '第一学段学生', word2: '简单的整数四则运算', dependency: '进行' },
        { word1: '第一学段学生', word2: '简单的整数四则运算', dependency: '运算' },
        { word1: '第一学段学生', word2: '第一学段学生', dependency: '形成' },
        { word1: '第一学段学生', word2: '简单的立体图形和平面图形', dependency: '辨认' },
        { word1: '第一学段学生', word2: '长方形和正方形的特征', dependency: '认识' },
        { word1: '第一学段学生', word2: '物体长度的测量过程', dependency: '体验' },
        { word1: '第一学段学生', word2: '物体长度', dependency: '测量' },
        { word1: '第一学段学生', word2: '初步的量感和空间观念', dependency: '认识' },
        { word1: '第一学段学生', word2: '初步的量感和空间观念', dependency: '形成' },
        { word1: '第一学段学生', word2: '简单的分类过程', dependency: '经历' },
        { word1: '第一学段学生', word2: '标准', dependency: '给定' },
        { word1: '第一学段学生', word2: '分类', dependency: '进行' },
        { word1: '第一学段学生', word2: '初步的数据意识', dependency: '形成' },
        { word1: '第一学段学生', word2: '初步的数据意识', dependency: '活动' },
        { word1: '第一学段学生', word2: '货币单位、时间单位和基本方向', dependency: '认识' },
        { word1: '第一学段学生', word2: '用数学方法解决问题', dependency: '尝试' },
        { word1: '第一学段学生', word2: '问题', dependency: '解决' },
        { word1: '第一学段学生', word2: '数学活动经验', dependency: '积累' },
        { word1: '第一学段学生', word2: '数学活动经验', dependency: '形成' },
        { word1: '第一学段学生', word2: '数学活动经验', dependency: '指导' },
        { word1: '第一学段学生', word2: '数学活动经验', dependency: '生活' },
        { word1: '第一学段学生', word2: '简单的数学问题', dependency: '提出' },
        { word1: '第一学段学生', word2: '简单的数学问题', dependency: '简单' },
        { word1: '第一学段学生', word2: '运用所学的知识和方法解决问题', dependency: '尝试' },
        { word1: '第一学段学生', word2: '所学的知识和方法', dependency: '运用' },
        { word1: '第一学段学生', word2: '知识和方法', dependency: '学' },
        { word1: '第一学段学生', word2: '数学问题', dependency: '解决' },
        { word1: '第一学段学生', word2: '分析问题和解决问题的基本方法', dependency: '感悟' },
        { word1: '第一学段学生', word2: '问题', dependency: '分析' },
        { word1: '第一学段学生', word2: '数学在生活中的应用', dependency: '感受' },
        { word1: '第一学段学生', word2: '数学在生活中的应用', dependency: '形成' },
        { word1: '第一学段学生', word2: '与数学', dependency: '有关' },
        { word1: '第一学段学生', word2: '好奇心', dependency: '有' },
        { word1: '第一学段学生', word2: '数学学习活动', dependency: '参与' },
        { word1: '第一学段学生', word2: '克服困难', dependency: '尝试' },
        { word1: '第一学段学生', word2: '困难', dependency: '克服' },
        { word1: '第一学段学生', word2: '数学活动中的成功', dependency: '感受' },
        { word1: '第一学段学生', word2: '数学与生活有密切联系', dependency: '了解' },
        { word1: '第一学段学生', word2: '生活中的一些现象', dependency: '描述' },
        { word1: '第一学段学生', word2: '数学与生活有密切联系', dependency: '感受' },
        { word1: '第一学段学生', word2: '数学与生活密切联系', dependency: '有' },
        { word1: '第一学段学生', word2: '数学美', dependency: '感受' },
        { word1: '第一学段学生', word2: '他人的意见', dependency: '倾听' },
        { word1: '第一学段学生', word2: '对他人的想法提出建议', dependency: '尝试' },
        { word1: '第一学段学生', word2: '建议', dependency: '提出' },
        { word1: '第一学段学生', word2: '生活经验和幼儿园相关活动经验', dependency: '利用' },
        { word1: '第一学段学生', word2: '生活经验和幼儿园相关活动经验', dependency: '具体' },
        { word1: '第一学段学生', word2: '生活经验和幼儿园相关活动经验', dependency: '生动活泼' },
        { word1: '第一学段学生', word2: '简单的数学内容', dependency: '学习' },
        { word1: '第一学段学生', word2: '认识20以内的数，会20以内数的加减法（不含退位减法），能辨认物体和简单图形的形状，会简单的分类，解决日常生活中的简单问题', dependency: '是' },
        { word1: '第一学段学生', word2: '20以内的数', dependency: '认识' },
        { word1: '第一学段学生', word2: '退位减法', dependency: '含' },
        { word1: '第一学段学生', word2: '物体和简单图形的形状', dependency: '辨认' },
        { word1: '第一学段学生', word2: '日常生活中的简单问题', dependency: '解决' },
        { word1: '第一学段学生', word2: '兴趣', dependency: '产生' },
        { word1: '第一学段学生', word2: '信心', dependency: '树立' },
        { word1: '第二学段学生', word2: '小数和分数', dependency: '认识' },
        { word1: '第二学段学生', word2: '小数和分数的形成过程', dependency: '经历' },
        { word1: '第二学段学生', word2: '较复杂的整数四则运算和简单的小数、分数的加减运算', dependency: '进行' },
        { word1: '第二学段学生', word2: '运算律', dependency: '理解' },
        { word1: '第二学段学生', word2: '运算律', dependency: '形成' },
        { word1: '第二学段学生', word2: '常见的平面图形', dependency: '认识' },
        { word1: '第二学段学生', word2: '平面图形的周长和面积的测量过程', dependency: '经历' },
        { word1: '第二学段学生', word2: '长方形周长和面积的计算方法', dependency: '探索' },
        { word1: '第二学段学生', word2: '长方形周长和面积', dependency: '计算' },
        { word1: '第二学段学生', word2: '图形的平移、旋转和轴对称', dependency: '了解' },
        { word1: '第二学段学生', word2: '图形的平移、旋转和轴对称', dependency: '形成' },
        { word1: '第二学段学生', word2: '简单的数据收集过程', dependency: '经历' },
        { word1: '第二学段学生', word2: '数据收集、整理和呈现的简单方法', dependency: '了解' },
        { word1: '第二学段学生', word2: '数据', dependency: '收集' },
        { word1: '第二学段学生', word2: '数据', dependency: '整理' },
        { word1: '第二学段学生', word2: '数据', dependency: '呈现' },
        { word1: '第二学段学生', word2: '平均数的意义', dependency: '理解' },
        { word1: '第二学段学生', word2: '问题', dependency: '解决' },
        { word1: '第二学段学生', word2: '问题', dependency: '形成' },
        { word1: '第二学段学生', word2: '时间单位和方向', dependency: '认识' },
        { word1: '第二学段学生', word2: '质量单位', dependency: '认识' },
        { word1: '第二学段学生', word2: '应用数学和其他学科知识与方法解决问题', dependency: '尝试' },
        { word1: '第二学段学生', word2: '数学和其他学科知识与方法', dependency: '应用' },
        { word1: '第二学段学生', word2: '数学活动经验', dependency: '积累' },
        { word1: '第二学段学生', word2: '数学活动经验', dependency: '形成' },
        { word1: '第二学段学生', word2: '从日常生活中发现和提出数学问题，探索分析和解决问题的方法', dependency: '尝试' },
        { word1: '第二学段学生', word2: '数学问题', dependency: '发现' },
        { word1: '第二学段学生', word2: '数学问题', dependency: '提出' },
        { word1: '第二学段学生', word2: '分析和解决问题的方法', dependency: '探索' },
        { word1: '第二学段学生', word2: '分析和解决问题的方法', dependency: '分析' },
        { word1: '第二学段学生', word2: '独立思考并与他人合作交流解决问题的过程', dependency: '经历' },
        { word1: '第二学段学生', word2: '独立思考并与他人合作交流解决问题的过程', dependency: '思考' },
        { word1: '第二学段学生', word2: '独立思考并与他人合作交流解决问题的过程', dependency: '合作' },
        { word1: '第二学段学生', word2: '解决问题', dependency: '交流' },
        { word1: '第二学段学生', word2: '数量关系', dependency: '常见' },
        { word1: '第二学段学生', word2: '结果的合理性', dependency: '判断' },
        { word1: '第二学段学生', word2: '初步的模型意识、几何直观和应用意识', dependency: '形成' },
        { word1: '第二学段学生', word2: '日常生活中与数学相关的信息', dependency: '了解' },
        { word1: '第二学段学生', word2: '日常生活中与数学相关的信息', dependency: '相关' },
        { word1: '第二学段学生', word2: '参与数学学习活动', dependency: '愿意' },
        { word1: '第二学段学生', word2: '数学学习活动', dependency: '参与' },
        { word1: '第二学段学生', word2: '数学学习活动', dependency: '鼓励' },
        { word1: '第二学段学生', word2: '数学学习活动', dependency: '引导' },
        { word1: '第二学段学生', word2: '克服困难、解决问题的成就', dependency: '体验' },
        { word1: '第二学段学生', word2: '困难', dependency: '克服' },
        { word1: '第二学段学生', word2: '数学的作用', dependency: '体会' },
        { word1: '第二学段学生', word2: '数学美', dependency: '体验' },
        { word1: '第二学段学生', word2: '自己的想法', dependency: '提出' },
        { word1: '第二学段学生', word2: '自己的想法', dependency: '交流' },
        { word1: '第二学段学生', word2: '自己的想法', dependency: '质疑' },
        { word1: '第二学段学生', word2: '自己的想法', dependency: '反思' },
        { word1: '第三学段学生', word2: '自然数的一些特征', dependency: '经历' },
        { word1: '第三学段学生', word2: '数', dependency: '表示' },
        { word1: '第三学段学生', word2: '自然数的一些特征', dependency: '认识' },
        { word1: '第三学段学生', word2: '小数和分数的意义', dependency: '理解' },
        { word1: '第三学段学生', word2: '小数和分数的四则运算', dependency: '进行' },
        { word1: '第三学段学生', word2: '小数和分数', dependency: '运算' },
        { word1: '第三学段学生', word2: '数运算的一致性', dependency: '探索' },
        { word1: '第三学段学生', word2: '数运算的一致性', dependency: '形成' },
        { word1: '第三学段学生', word2: '几何图形面积和体积的计算方法', dependency: '探索' },
        { word1: '第三学段学生', word2: '常见平面图形的周长和面积', dependency: '计算' },
        { word1: '第三学段学生', word2: '常见立体图形的体积和表面积', dependency: '计算' },
        { word1: '第三学段学生', word2: '序数', dependency: '有' },
        { word1: '第三学段学生', word2: '点的位置', dependency: '确定' },
        { word1: '第三学段学生', word2: '图形的平移、旋转和轴对称', dependency: '认识' },
        { word1: '第三学段学生', word2: '量感、空间观念和几何直观', dependency: '形成' },
        { word1: '第三学段学生', word2: '收集、整', dependency: '经历' },
        { word1: '第三学段学生', word2: '数据', dependency: '表达' },
        { word1: '第三学段学生', word2: '理和表达数据的过程', dependency: '表达' },
        { word1: '第三学段学生', word2: '理和表达数据的过程简单的判断', dependency: '作出' },
        { word1: '第三学段学生', word2: '随机现象发生的可能性', dependency: '理解' },
        { word1: '第三学段学生', word2: '随机现象发生的可能性', dependency: '了解' },
        { word1: '第三学段学生', word2: '随机现象发生的可能性', dependency: '发生' },
        { word1: '第三学段学生', word2: '理和表达数据的过程', dependency: '形成' },
        { word1: '第三学段学生', word2: '数学', dependency: '了解' },
        { word1: '第三学段学生', word2: '数学和其他学科知识与方法', dependency: '应用' },
        { word1: '第三学段学生', word2: '问题', dependency: '解决' },
        { word1: '第三学段学生', word2: '数学活动经验', dependency: '积累' },
        { word1: '第三学段学生', word2: '数学活动经验', dependency: '形成' },
        { word1: '第三学段学生', word2: '运用基本的数量关系，以及几何直观、逻辑推理和其他学科的知识、方法分析与解决问题，形成模型意识和初步的应用意识、创新意识', dependency: '尝试' },
        { word1: '第三学段学生', word2: '问题', dependency: '发现' },
        { word1: '第三学段学生', word2: '问题', dependency: '提出' },
        { word1: '第三学段学生', word2: '运用基本的', dependency: '探索' },
        { word1: '第三学段学生', word2: '基本的数量关系，以及几何直观、逻辑推理和其他学科的知识、方法', dependency: '运用' },
        { word1: '第三学段学生', word2: '问题', dependency: '分析' },
        { word1: '第三学段学生', word2: '在真实的情境中', dependency: '形成' },
        { word1: '第三学段学生', word2: '好奇心和求知欲', dependency: '具有' },
        { word1: '第三学段学生', word2: '数学学习活动', dependency: '参与' },
        { word1: '第三学段学生', word2: '题', dependency: '解决' },
        { word1: '第三学段学生', word2: '成功的乐趣', dependency: '体验' },
        { word1: '第三学段学生', word2: '自己能够学好数学，感受数学的价值，体验并欣赏数学美', dependency: '相信' },
        { word1: '第三学段学生', word2: '数学', dependency: '学好' },
        { word1: '第三学段学生', word2: '数学的价值', dependency: '感受' },
        { word1: '第三学段学生', word2: '数学美', dependency: '体验' },
        { word1: '第三学段学生', word2: '数学美', dependency: '欣赏' },
        { word1: '第三学段学生', word2: '认真勤奋、独立思考、合作交流、反思质疑的习惯', dependency: '养成' },
        { word1: '第三学段学生', word2: '认真勤奋、独立思考、合作交流、反思质疑的习惯', dependency: '思考' },
        { word1: '第四学段学生', word2: '有理数、实数的形成过程', dependency: '经历' },
        { word1: '第四学段学生', word2: '有理数、实数', dependency: '形成' },
        { word1: '第四学段学生', word2: '数与式的运算', dependency: '理解' },
        { word1: '第四学段学生', word2: '运算结果的意义', dependency: '掌握' },
        { word1: '第四学段学生', word2: '运算结果的意义', dependency: '解释' },
        { word1: '第四学段学生', word2: '现实问题中的数量关系和变化规律', dependency: '描述' },
        { word1: '第四学段学生', word2: '现实问题中的数量关系和变化规律', dependency: '形成' },
        { word1: '第四学段学生', word2: '现实问题中的数量关系和变化规律', dependency: '合适' },
        { word1: '第四学段学生', word2: '问题', dependency: '解决' },
        { word1: '第四学段学生', word2: '问题', dependency: '形成' },
        { word1: '第四学段学生', word2: '运算能力', dependency: '发展' },
        { word1: '第四学段学生', word2: '探索图形特征的过程', dependency: '经历' },
        { word1: '第四学段学生', word2: '图形特征', dependency: '探索' },
        { word1: '第四学段学生', word2: '基本的几何概念', dependency: '建立' },
        { word1: '第四学段学生', word2: '平面图形的性质与关系', dependency: '理解' },
        { word1: '第四学段学生', word2: '基本的几何证明方法', dependency: '掌握' },
        { word1: '第四学段学生', word2: '平移、旋转和轴对称的基本特征', dependency: '知道' },
        { word1: '第四学段学生', word2: '平移、旋转和轴对称的基本特征', dependency: '对称' },
        { word1: '第四学段学生', word2: '平面直角坐标系', dependency: '理解' },
        { word1: '第四学段学生', word2: '平面直角坐标系', dependency: '认识' },
        { word1: '第四学段学生', word2: '推理能力', dependency: '描述' },
        { word1: '第四学段学生', word2: '推理能力', dependency: '形成' },
        { word1: '第四学段学生', word2: '空间观念和几何直观', dependency: '发展' },
        { word1: '第四学段学生', word2: '数据收集与整理的基本方法', dependency: '掌握' },
        { word1: '第四学段学生', word2: '数据', dependency: '收集' },
        { word1: '第四学段学生', word2: '数据', dependency: '整理' },
        { word1: '第四学段学生', word2: '随机现象', dependency: '理解' },
        { word1: '第四学段学生', word2: '利用统计图表表示数据的方法', dependency: '探索' },
        { word1: '第四学段学生', word2: '统计图表', dependency: '利用' },
        { word1: '第四学段学生', word2: '数据', dependency: '表示' },
        { word1: '第四学段学生', word2: '各种统计图表的功能', dependency: '理解' },
        { word1: '第四学段学生', word2: '利用样本推断总体的过程', dependency: '经历' },
        { word1: '第四学段学生', word2: '样本', dependency: '利用' },
        { word1: '第四学段学生', word2: '总体', dependency: '推断' },
        { word1: '第四学段学生', word2: '平均数、方差、四分位数等基本统计量', dependency: '计算' },
        { word1: '第四学段学生', word2: '频数、频率和概率的意义', dependency: '了解' },
        { word1: '第四学段学生', word2: '频数、频率和概率的意义', dependency: '形成' },
        { word1: '第四学段学生', word2: '在不同的情境中从数学的角度发现和提出问题', dependency: '探索' },
        { word1: '第四学段学生', word2: '在不同的情境中从数学的角度发现和提出问题', dependency: '发现' },
        { word1: '第四学段学生', word2: '问题', dependency: '提出' },
        { word1: '第四学段学生', word2: '数学和其他学科的知识', dependency: '运用' },
        { word1: '第四学段学生', word2: '分析问题和解决问题的方法', dependency: '寻求' },
        { word1: '第四学段学生', word2: '问题', dependency: '分析' },
        { word1: '第四学段学生', word2: '几何直观、逻辑推理等方法', dependency: '运用' },
        { word1: '第四学段学生', word2: '问题', dependency: '合作' },
        { word1: '第四学段学生', word2: '问题', dependency: '交流' },
        { word1: '第四学段学生', word2: '自己的观点', dependency: '表达' },
        { word1: '第四学段学生', word2: '他人的思考方法和结论', dependency: '理解' },
        { word1: '第四学段学生', word2: '解决问题的思考过程', dependency: '回顾' },
        { word1: '第四学段学生', word2: '解决问题的方法和结论', dependency: '反思' },
        { word1: '第四学段学生', word2: '社会生活中与数学相关的信息', dependency: '关注' },
        { word1: '第四学段学生', word2: '数学问题', dependency: '参与' },
        { word1: '第四学段学生', word2: '数学问题', dependency: '活动' },
        { word1: '第四学段学生', word2: '困难', dependency: '解决' },
        { word1: '第四学段学生', word2: '困难', dependency: '克服' },
        { word1: '第四学段学生', word2: '学好数学的信心', dependency: '树立' },
        { word1: '第四学段学生', word2: '数学', dependency: '学好' },
        { word1: '第四学段学生', word2: '数学在实际生活中的应用', dependency: '感受' },
        { word1: '第四学段学生', word2: '数学', dependency: '应用' },
        { word1: '第四学段学生', word2: '数学的价值', dependency: '体会' },
        { word1: '第四学段学生', word2: '数学美', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '创造数学美', dependency: '尝试' },
        { word1: '第四学段学生', word2: '数学美', dependency: '创造' },
        { word1: '第四学段学生', word2: '认真勤奋、独立思考、合作交流、反思质疑的学习习惯', dependency: '养成' },
        { word1: '数学', word2: '第一学段学生', dependency: '阶段' },
        { word1: '数学', word2: '第二学段学生', dependency: '阶段' },
        { word1: '数学', word2: '第三学段学生', dependency: '阶段' },
        { word1: '数学', word2: '第四学段学生', dependency: '阶段' },
      ],
    }
  },
}
</script>

<style></style>
