<template>
  <div>
    <knowledge-graph :word="word" :relationship="relationship" :subjectName="subjectName"></knowledge-graph>
  </div>
</template>

<script>
import knowledgeGraph from '@/components/works/knowledgeGraph'
export default {
  components: { knowledgeGraph },
  data() {
    return {
      subjectName: '艺术',
      word: [
        '第一学段学生',
        '简单评价',
        '影视（含数字媒体艺术）作品的形态特征',
        '音乐的感性特征和审美特质',
        '戏 剧',
        '设计能改善和美化我们的生活',
        '态度',
        '影视（含数字媒体艺术）在传承和弘扬中华优秀传统文化、革命文化、社会主义先 进文化，感悟伟大建党精神过程中的重要作用',
        '艺术表现的乐趣',
        '音乐的感性特 征和审美特质',
        '对影视（含数字媒体艺术）作品',
        '实践经验',
        '创作',
        '中国传统工艺',
        '音 乐作品',
        '事 物',
        '中国音乐文化',
        '中国音乐文化中的中华美育精神和民族审美特质',
        '音乐',
        '一定的想象力和创造力',
        '自己的想法和感受',
        '家乡',
        '对自然与社会的感受、思考和认识',
        '对他人及自我',
        '较浓厚的兴趣',
        '数字媒体艺术',
        '作品中',
        '对美好事 物的',
        '环境规划',
        '身心',
        '表达自己独特的感受和想法',
        '校园现实生活',
        '初步的音 乐欣赏与评述能力',
        '不同音乐的表达方式',
        '所见所闻、所感所想',
        '音乐情绪',
        '“实用与美观相结合"的设计原则',
        '自己独特的感受和想法',
        '背景',
        '音乐与姊妹艺术、其他学科，以及个人、自然、生活、社会、科技的广泛联系',
        '良好的欣赏习惯',
        '运用多种艺术手段进行戏剧演出的基本能力',
        '简单评述',
        '社会生活和社会文化中的音乐现象',
        '工具、材料和媒介',
        '文 化',
        '与音乐作品的情感',
        '自己的所见所闻、所感所想',
        '红色基因',
        '音乐表现活动',
        '丰富的音乐情绪与情感体验',
        '戏剧编演的方法',
        '初步欣赏和分析',
        '人类命运共同体',
        '积极乐观的态度',
        '我们',
        '爱党、爱国、爱家乡的情感',
        '艺术',
        '戏剧（含戏曲）活动',
        '与同伴合作的意识和团队精神',
        '社会责任感',
        '中国音乐文化和世界多元音乐文化',
        '伟大建党精神',
        '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏剧表演等艺术活动',
        '音 乐',
        '中外戏剧艺术的不 同文化背景',
        '民族精神、时代精神等',
        '戏剧演出',
        '美术对个人发展、社会进步及构建人类命运共同体具有独 特的作用',
        '自己的个性化理解和创意',
        '审美特征',
        '乐观的态度以及对身边人的友爱之情',
        '事物',
        '与他人',
        '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏 剧表演等艺术活动',
        '规则意识和合作意识',
        '环境',
        '中华民族自豪感',
        '交流与合作能力',
        '身体语言',
        '独立解放',
        '不同体裁和风格的舞蹈',
        '某件物 品',
        '文化视野',
        '创意活动',
        '感受和想法',
        '工艺 师敬业、专注和精益求精的工匠精神',
        '自己的情感',
        '文 化差异',
        '欣赏习惯',
        '美存在于我们周边',
        '物品',
        '创造性思维能力',
        '社会责任',
        '美术与姊妹艺术',
        '自己的改进意见',
        '对我国优秀民族舞蹈文化的学习与传承',
        '传统工艺“守正创新"的内涵与意义',
        '工艺 师',
        '中国戏曲艺术',
        '不同音乐表现特征的差异与联系',
        '表现形式',
        '独 特的作用',
        '音乐的情绪与情感',
        '对音乐的浓厚兴趣',
        '中华民族追求独立解放和党团结带领人民进行革命、建设、改革',
        '自己的想法和情 感',
        '戏曲',
        '综合融通',
        '学科，以及信息科技等课程的学习',
        '艺术表现活动',
        '社会主义核心价值观',
        '工具、材料和技能',
        '文化自 信',
        '对音乐感 性特征和审美特质',
        '世界美术的多样性和差异性',
        '创意表达能力',
        '与同伴',
        '简单的音 乐作品',
        '音乐的基本特征',
        '世界不同国家和地区的美术作品',
        '自己的发现和感受',
        '个性和创意',
        '学段学生',
        '艺术表现能力',
        '影视（含数字媒体艺术）作品的主要类型、风格与流派',
        '自主学习能力和团队合作能力',
        '审美和人文素养',
        '对我国优秀民族舞蹈文化',
        '“设计满足实用功能与审美价值，传递社会责任”的设计原则',
        '音乐作品',
        '创新思维能力',
        '综合探索与学习迁移的能力',
        '工具和材料',
        '班级或小组',
        '对中国音乐文化',
        '社会主 义',
        '第二学段学生',
        '对中国音乐文化的了解和喜爱之情',
        '艺术家的作品',
        '创意',
        '对他人及自我的理解',
        '继承与发展文化遗产是我们的责任',
        '规则',
        '工 艺品',
        '规则意识、责任意识和学习意志力等',
        '初步的了解',
        '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用',
        '美术产生的背景及不同时代、地区、民族和国家的美术特 征',
        '不同舞种的舞蹈姿态与基本动作',
        '不同的工具和材料',
        '想象力和创造力',
        '正',
        '身心健康成长',
        '人民进行革命、建设、改革',
        '不同艺术的主要表现形式、表现手段和审美特征',
        '人与自然',
        '作品',
        '对美好事 物',
        '传统或现代的工具、材料和媒介',
        '对戏剧（含戏曲）艺术作品',
        '中华民族',
        '美术知 识、技能和思维方式',
        '多种艺术手段',
        '世界音乐文化的多样性',
        '参与多种与音乐相关的艺术表现活动，展现自己的个性化理解和创意',
        '影视（含数字媒体艺术）与真实世界、虚拟世界的联系',
        '设计',
        '造型游戏活动',
        '个人、自然、生活、社会、科技',
        '中华民族文化艺术的瑰宝',
        '平面、立体或动态等表现形式的美术作 品',
        '对音乐的兴趣',
        '美术',
        '戏剧',
        '国家认同 感、归属感、责任感和使命感',
        '歌',
        '革命、建设、改革',
        '爱党、爱国、爱社会主 义的情感和乐观的态度，以及对美好事物的热爱之情',
        '作品中蕴含的爱国主义、集体主义',
        '对美好事物',
        '工艺品',
        '富有个性和创意的二度创作及表现形式的创新',
        '个人',
        '中华优秀传统文化、革命文化、社会主义先 进文化',
        '平面、立体或动态等表现形式的美术作品',
        '音乐的艺术形象',
        '剧目',
        '党',
        '物品的特点',
        '社会',
        '“教育戏剧”“教育剧场”的方法',
        '观剧感受和见解',
        '造型元素、形式原理和欣赏方法',
        '影视（含数字媒体艺术）作品',
        '中外舞蹈艺术特色',
        '一定的戏剧应 用活动',
        '传统工艺',
        '团队',
        '文 化自信',
        '传统工艺品或文创产品',
        '实用功能与审美价值',
        '各种问题',
        '传统工艺品',
        '制作工 艺品',
        '实用与美观',
        '较丰富的想象力和创造力',
        '传统与现代的工具、材料和媒介，以及习得的美术知 识、技能和思维方式',
        '中外美术作品的魅力',
        '第三学段学生',
        '尊 重、理解和包容的态度',
        '开放包容的心态和人类命运共同体意识',
        '多种艺术表现形式',
        '对伟 大祖国、中华民族的情感',
        '人类',
        '自己的想法',
        '简单的数字设备和软件',
        '班级或小组开展的美术与姊妹艺术及其他学科相结 合的造型游戏活动',
        '声音与音乐',
        '舞蹈美的丰富性',
        '文化自信',
        '学生',
        '班级、学校',
        '影视（含数字媒体艺术）与真实世界、虚拟世界',
        '音乐欣赏和评述能力',
        '守规则、负责任等良好品质',
        '情感、观念和想象',
        '社会主义',
        '音乐的思想感情和内涵意蕴',
        '民族文化智慧',
        '不同的工具、材料和技能',
        '作用',
        '装饰和美化',
        '中外戏剧艺术史的基本常识',
        '影视（含数字媒体艺术）作品的制作流程',
        '身边的美',
        '影视艺术思维、数字媒体思维、信息思维和科技思维等',
        '，以及个人、自然、生活、社会、科技的联系',
        '社会责任意识',
        '不同音乐表现特征',
        '爱党、爱国、爱社会主义的情感',
        '综 合探索与学习迁移的能力',
        '初步表达观剧感受和见解的能力',
        '对音乐作品和音乐活动',
        '中国传统工艺是中华民族文化艺术的瑰宝',
        '自信心',
        '不同的工具、材料和媒介',
        '多种与音乐相关的艺术表现活动',
        '学校或社区',
        '校园微电影',
        '比较完整的短小音乐作品',
        '世界多元音乐文化',
        '中国戏曲艺术所具有的独特的审美特征',
        '影视（含数字媒体艺术）的基本创作技巧和艺术语言',
        '舞蹈',
        '对音乐感 性特征和审美特质的感知、体验与理解',
        '非物质文化遗产的含义',
        '文化遗产',
        '创意实践能力和艺术表现水平',
        '其他艺术学科，以及信息科技等课程',
        '继承与发展文化遗产',
        '我们的责任',
        '影视（含数字媒体艺术）',
        '美术作品',
        '兴趣',
        '自己',
        '数字设备和软件',
        '剧',
        '第四学段学生',
        '好奇心和探究欲',
        '美的',
        '脚本',
        '我们的生活',
        '乐观的态度以及对美好事 物的关爱之情',
      ],
      relationship: [
        { word1: '第一学段学生', word2: '音乐的情绪与情感', dependency: '体验' },
        { word1: '第一学段学生', word2: '音乐的基本特征', dependency: '了解' },
        { word1: '第一学段学生', word2: '音乐的艺术形象', dependency: '感知' },
        { word1: '第一学段学生', word2: '兴趣', dependency: '产生' },
        { word1: '第一学段学生', word2: '爱党、爱国、爱家乡的情感', dependency: '唤起' },
        { word1: '第一学段学生', word2: '党', dependency: '爱' },
        { word1: '第一学段学生', word2: '家乡', dependency: '爱' },
        { word1: '第一学段学生', word2: '乐观的态度以及对身边人的友爱之情', dependency: '具有' },
        { word1: '态度', word2: '乐观的态度以及对身边人的友爱之情', dependency: '乐观' },
        { word1: '第一学段学生', word2: '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏 剧表演等艺术活动', dependency: '参与' },
        { word1: '第一学段学生', word2: '歌', dependency: '表演' },
        { word1: '第一学段学生', word2: '戏 剧', dependency: '表演' },
        { word1: '第一学段学生', word2: '戏 剧', dependency: '活动' },
        { word1: '第一学段学生', word2: '实践经验', dependency: '积累' },
        { word1: '第一学段学生', word2: '艺术表现的乐趣', dependency: '享受' },
        { word1: '第一学段学生', word2: '艺术', dependency: '表现' },
        { word1: '第一学段学生', word2: '艺术', dependency: '实践' },
        { word1: '第一学段学生', word2: '规则意识和合作意识', dependency: '建立' },
        { word1: '第一学段学生', word2: '好奇心和探究欲', dependency: '有' },
        { word1: '第一学段学生', word2: '声音与音乐', dependency: '探究' },
        { word1: '第一学段学生', word2: '自己的想法和感受', dependency: '表达' },
        { word1: '自己', word2: '自己的想法和感受', dependency: '感受' },
        { word1: '第一学段学生', word2: '中国音乐文化和世界多元音乐文化', dependency: '了解' },
        { word1: '学生', word2: '自己的发现和感受', dependency: '分享' },
        { word1: '学生', word2: '自己的发现和感受', dependency: '交流' },
        { word1: '自己', word2: '自己的发现和感受', dependency: '发现' },
        { word1: '学生', word2: '身边的美', dependency: '感知' },
        { word1: '学生', word2: '美存在于我们周边', dependency: '认识' },
        { word1: '学生', word2: '美存在于我们周边', dependency: '形成' },
        { word1: '学生', word2: '美的', dependency: '欣赏' },
        { word1: '学生', word2: '不同的工具、材料和媒介', dependency: '使用' },
        { word1: '工具、材料和媒介', word2: '不同的工具、材料和媒介', dependency: '不同' },
        { word1: '学生', word2: '所见所闻、所感所想', dependency: '表达' },
        { word1: '学生', word2: '物品', dependency: '使用' },
        { word1: '学生', word2: '物品的特点', dependency: '了解' },
        { word1: '学生', word2: '某件物 品', dependency: '设计' },
        { word1: '学生', word2: '自己的改进意见', dependency: '提出' },
        { word1: '学生', word2: '装饰和美化', dependency: '进行' },
        { word1: '学生', word2: '装饰和美化', dependency: '装饰' },
        { word1: '学生', word2: '装饰和美化', dependency: '形成' },
        { word1: '学生', word2: '不同的工具、材料和媒介', dependency: '利用' },
        { word1: '工具、材料和媒介', word2: '传统工艺', dependency: '体验' },
        { word1: '工具、材料和媒介', word2: '制作工 艺品', dependency: '学习' },
        { word1: '工具、材料和媒介', word2: '工 艺品', dependency: '制作' },
        { word1: '工具、材料和媒介', word2: '中国传统工艺是中华民族文化艺术的瑰宝', dependency: '知道' },
        { word1: '中国传统工艺', word2: '中华民族文化艺术的瑰宝', dependency: '是' },
        { word1: '中国传统工艺', word2: '中华民族自豪感', dependency: '增强' },
        { word1: '中国传统工艺', word2: '班级或小组开展的美术与姊妹艺术及其他学科相结 合的造型游戏活动', dependency: '参与' },
        { word1: '班级或小组', word2: '美术与姊妹艺术', dependency: '开展' },
        { word1: '班级或小组', word2: '造型游戏活动', dependency: '结 合' },
        { word1: '班级或小组', word2: '造型游戏活动', dependency: '活动' },
        { word1: '班级或小组', word2: '综合探索与学习迁移的能力', dependency: '形成' },
        { word1: '班级或小组', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第二学段学生', word2: '丰富的音乐情绪与情感体验', dependency: '具有' },
        { word1: '第二学段学生', word2: '音乐情绪', dependency: '丰富' },
        { word1: '第二学段学生', word2: '音乐情绪', dependency: '体验' },
        { word1: '与音乐作品的情感', word2: '音乐情绪', dependency: '共鸣' },
        { word1: '与音乐作品的情感', word2: '爱党、爱国、爱社会主义的情感', dependency: '焕发' },
        { word1: '与音乐作品的情感', word2: '党', dependency: '爱' },
        { word1: '与音乐作品的情感', word2: '社会主义', dependency: '爱' },
        { word1: '与音乐作品的情感', word2: '乐观的态度以及对美好事 物的关爱之情', dependency: '具有' },
        { word1: '态度', word2: '乐观的态度以及对美好事 物的关爱之情', dependency: '乐观' },
        { word1: '事 物', word2: '乐观的态度以及对美好事 物的关爱之情', dependency: '美好' },
        { word1: '事 物', word2: '对美好事 物', dependency: '关爱' },
        { word1: '事 物', word2: '对美好事 物的', dependency: '感知' },
        { word1: '事 物', word2: '对美好事 物', dependency: '体验' },
        { word1: '学生', word2: '音乐的感性特征和审美特质', dependency: '了解' },
        { word1: '学生', word2: '良好的欣赏习惯', dependency: '养成' },
        { word1: '欣赏习惯', word2: '良好的欣赏习惯', dependency: '良好' },
        { word1: '欣赏习惯', word2: '简单评价', dependency: '进行' },
        { word1: '欣赏习惯', word2: '对音乐作品和音乐活动', dependency: '评价' },
        { word1: '欣赏习惯', word2: '对音乐的兴趣', dependency: '增强' },
        { word1: '第二学段学生', word2: '演唱、演奏、歌表演、律动、音乐游戏、舞蹈、戏剧表演等艺术活动', dependency: '进行' },
        { word1: '第二学段学生', word2: '戏剧', dependency: '表演' },
        { word1: '学生', word2: '戏剧', dependency: '活动' },
        { word1: '第二学段学生', word2: '表达自己独特的感受和想法', dependency: '乐于' },
        { word1: '第二学段学生', word2: '自己独特的感受和想法', dependency: '表达' },
        { word1: '感受和想法', word2: '自己独特的感受和想法', dependency: '独特' },
        { word1: '自己', word2: '自己独特的感受和想法', dependency: '感受' },
        { word1: '第二学段学生', word2: '规则意识、责任意识和学习意志力等', dependency: '增强' },
        { word1: '第二学段学生', word2: '交流与合作能力', dependency: '发展' },
        { word1: '第二学段学生', word2: '好奇心和探究欲', dependency: '保持' },
        { word1: '第二学段学生', word2: '好奇心和探究欲', dependency: '表演' },
        { word1: '第二学段学生', word2: '艺术', dependency: '编创' },
        { word1: '第二学段学生', word2: '艺术', dependency: '创造' },
        { word1: '第二学段学生', word2: '艺术', dependency: '活动' },
        { word1: '学生', word2: '个性和创意', dependency: '展现' },
        { word1: '第二学段学生', word2: '对中国音乐文化的了解和喜爱之情', dependency: '增进' },
        { word1: '第二学段学生', word2: '对中国音乐文化', dependency: '了解' },
        { word1: '学生', word2: '世界多元音乐文化', dependency: '了解' },
        { word1: '学生', word2: '文化视野', dependency: '开阔' },
        { word1: '第二学段学生', word2: '社会生活和社会文化中的音乐现象', dependency: '关注' },
        { word1: '第二学段学生', word2: '个人、自然、生活、社会、科技', dependency: '联系' },
        { word1: '学生', word2: '初步的了解', dependency: '有' },
        { word1: '学生', word2: '，以及个人、自然、生活、社会、科技的联系', dependency: '了解' },
        { word1: '第二学段学生', word2: '造型元素、形式原理和欣赏方法', dependency: '运用' },
        { word1: '第二学段学生', word2: '艺术家的作品', dependency: '欣赏' },
        { word1: '学生', word2: '艺术家的作品', dependency: '评述' },
        { word1: '第二学段学生', word2: '中外美术作品的魅力', dependency: '感受' },
        { word1: '第二学段学生', word2: '传统或现代的工具、材料和媒介', dependency: '运用' },
        { word1: '第二学段学生', word2: '平面、立体或动态等表现形式的美术作品', dependency: '创作' },
        { word1: '第二学段学生', word2: '自己的所见所闻、所感所想', dependency: '表达' },
        { word1: '与他人', word2: '自己的所见所闻、所感所想', dependency: '交流' },
        { word1: '第二学段学生', word2: '“实用与美观相结合"的设计原则', dependency: '了解' },
        { word1: '第二学段学生', word2: '实用与美观', dependency: '结合' },
        { word1: '班级、学校', word2: '实用与美观', dependency: '活动' },
        { word1: '第二学段学生', word2: '物品', dependency: '设计' },
        { word1: '第二学段学生', word2: '设计能改善和美化我们的生活', dependency: '体会' },
        { word1: '设计', word2: '我们的生活', dependency: '改善' },
        { word1: '设计', word2: '我们的生活', dependency: '美化' },
        { word1: '我们', word2: '我们的生活', dependency: '生活' },
        { word1: '第二学段学生', word2: '不同的工具、材料和技能', dependency: '利用' },
        { word1: '工具、材料和技能', word2: '不同的工具、材料和技能', dependency: '不同' },
        { word1: '第二学段学生', word2: '传统工艺品', dependency: '制作' },
        { word1: '第二学段学生', word2: '工艺 师敬业、专注和精益求精的工匠精神', dependency: '学习' },
        { word1: '工艺 师', word2: '工艺 师敬业、专注和精益求精的工匠精神', dependency: '敬业' },
        { word1: '工艺 师', word2: '工艺 师敬业、专注和精益求精的工匠精神', dependency: '精益求精' },
        { word1: '第二学段学生', word2: '美术', dependency: '融合' },
        { word1: '第二学段学生', word2: '各种问题', dependency: '探究' },
        { word1: '第二学段学生', word2: '综 合探索与学习迁移的能力', dependency: '提高' },
        { word1: '第二学段学生', word2: '综 合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第三学段学生', word2: '音乐的思想感情和内涵意蕴', dependency: '领悟' },
        { word1: '第三学段学生', word2: '爱党、爱国、爱社会主 义的情感和乐观的态度，以及对美好事物的热爱之情', dependency: '增强' },
        { word1: '第三学段学生', word2: '党', dependency: '爱' },
        { word1: '第三学段学生', word2: '社会主 义', dependency: '爱' },
        { word1: '事物', word2: '社会主 义', dependency: '美好' },
        { word1: '事物', word2: '对美好事物', dependency: '热爱' },
        { word1: '事物', word2: '对音乐感 性特征和审美特质的感知、体验与理解', dependency: '加深' },
        { word1: '事物', word2: '对音乐感 性特征和审美特质', dependency: '感知' },
        { word1: '事物', word2: '对音乐感 性特征和审美特质', dependency: '理解' },
        { word1: '事物', word2: '音乐欣赏和评述能力', dependency: '提高' },
        { word1: '事物', word2: '音乐', dependency: '欣赏' },
        { word1: '事物', word2: '音乐', dependency: '评述' },
        { word1: '第三学段学生', word2: '较浓厚的兴趣', dependency: '有' },
        { word1: '兴趣', word2: '较浓厚的兴趣', dependency: '浓厚' },
        { word1: '第三学段学生', word2: '参与多种与音乐相关的艺术表现活动，展现自己的个性化理解和创意', dependency: '乐于' },
        { word1: '第三学段学生', word2: '多种与音乐相关的艺术表现活动', dependency: '参与' },
        { word1: '艺术表现活动', word2: '多种与音乐相关的艺术表现活动', dependency: '相关' },
        { word1: '艺术表现活动', word2: '多种与音乐相关的艺术表现活动', dependency: '表现' },
        { word1: '艺术表现活动', word2: '多种与音乐相关的艺术表现活动', dependency: '活动' },
        { word1: '第三学段学生', word2: '自己的个性化理解和创意', dependency: '展现' },
        { word1: '自己', word2: '自己的个性化理解和创意', dependency: '理解' },
        { word1: '第三学段学生', word2: '交流与合作能力', dependency: '增强' },
        { word1: '第三学段学生', word2: '守规则、负责任等良好品质', dependency: '养成' },
        { word1: '第三学段学生', word2: '规则', dependency: '守' },
        { word1: '第三学段学生', word2: '自己的情感', dependency: '选用' },
        { word1: '音乐作品', word2: '自己的情感', dependency: '合适' },
        { word1: '第三学段学生', word2: '自己的情感', dependency: '表达' },
        { word1: '第三学段学生', word2: '简单的音 乐作品', dependency: '编创' },
        { word1: '第三学段学生', word2: '简单的音 乐作品', dependency: '展示' },
        { word1: '音 乐作品', word2: '简单的音 乐作品', dependency: '简单' },
        { word1: '第三学段学生', word2: '一定的想象力和创造力', dependency: '具有' },
        { word1: '第三学段学生', word2: '中国音乐文化中的中华美育精神和民族审美特质', dependency: '理解' },
        { word1: '第三学段学生', word2: '文 化自信', dependency: '增强' },
        { word1: '第三学段学生', word2: '文 化', dependency: '自信' },
        { word1: '第三学段学生', word2: '世界多元音乐文化', dependency: '了解' },
        { word1: '第三学段学生', word2: '世界多元音乐文化', dependency: '尊重' },
        { word1: '第三学段学生', word2: '音乐与姊妹艺术、其他学科，以及个人、自然、生活、社会、科技的广泛联系', dependency: '理解' },
        { word1: '第三学段学生', word2: '个人、自然、生活、社会、科技', dependency: '联系' },
        { word1: '第三学段学生', word2: '自己的想法', dependency: '有' },
        { word1: '第三学段学生', word2: '造型元素、形式原理和欣赏方法', dependency: '运用' },
        { word1: '第三学段学生', word2: '世界不同国家和地区的美术作品', dependency: '欣赏' },
        { word1: '第三学段学生', word2: '世界不同国家和地区的美术作品', dependency: '评述' },
        { word1: '第三学段学生', word2: '世界美术的多样性和差异性', dependency: '领略' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '养成' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '尊 重' },
        { word1: '第三学段学生', word2: '尊 重、理解和包容的态度', dependency: '理解' },
        { word1: '第三学段学生', word2: '传统与现代的工具、材料和媒介，以及习得的美术知 识、技能和思维方式', dependency: '运用' },
        { word1: '第三学段学生', word2: '美术知 识、技能和思维方式', dependency: '习得' },
        { word1: '第三学段学生', word2: '平面、立体或动态等表现形式的美术作 品', dependency: '创作' },
        { word1: '第三学段学生', word2: '创意表达能力', dependency: '提升' },
        { word1: '第三学段学生', word2: '创意', dependency: '表达' },
        { word1: '人与自然', word2: '创意', dependency: '共生' },
        { word1: '第三学段学生', word2: '环境规划', dependency: '进行' },
        { word1: '第三学段学生', word2: '环境', dependency: '规划' },
        { word1: '第三学段学生', word2: '社会责任意识', dependency: '增强' },
        { word1: '第三学段学生', word2: '不同的工具和材料', dependency: '利用' },
        { word1: '工具和材料', word2: '不同的工具和材料', dependency: '不同' },
        { word1: '第三学段学生', word2: '工艺品', dependency: '制作' },
        { word1: '第三学段学生', word2: '工艺品', dependency: '创作' },
        { word1: '第三学段学生', word2: '传统工艺“守正创新"的内涵与意义', dependency: '体会' },
        { word1: '第三学段学生', word2: '正', dependency: '守' },
        { word1: '第三学段学生', word2: '校园现实生活', dependency: '结合' },
        { word1: '第三学段学生', word2: '校园微电影', dependency: '创编' },
        { word1: '第三学段学生', word2: '综合探索与学习迁移的能力', dependency: '增强' },
        { word1: '第三学段学生', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第四学段学生', word2: '音乐的思想感情和内涵意蕴', dependency: '把握' },
        { word1: '第四学段学生', word2: '作品中蕴含的爱国主义、集体主义', dependency: '理解' },
        { word1: '作品中', word2: '作品中蕴含的爱国主义、集体主义', dependency: '蕴含' },
        { word1: '作品中', word2: '民族精神、时代精神等', dependency: '体悟' },
        { word1: '第四学段学生', word2: '国家认同 感、归属感、责任感和使命感', dependency: '增强' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '感知' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '体验' },
        { word1: '第四学段学生', word2: '音乐的感性特 征和审美特质', dependency: '理解' },
        { word1: '第四学段学生', word2: '不同音乐表现特征的差异与联系', dependency: '辨识' },
        { word1: '第四学段学生', word2: '音乐', dependency: '表现' },
        { word1: '不同音乐表现特征', word2: '音乐', dependency: '联系' },
        { word1: '不同音乐表现特征', word2: '初步的音 乐欣赏与评述能力', dependency: '具有' },
        { word1: '不同音乐表现特征', word2: '音 乐', dependency: '欣赏' },
        { word1: '不同音乐表现特征', word2: '音 乐', dependency: '评述' },
        { word1: '学生', word2: '对音乐的浓厚兴趣', dependency: '保持' },
        { word1: '学生', word2: '积极乐观的态度', dependency: '养成' },
        { word1: '态度', word2: '积极乐观的态度', dependency: '乐观' },
        { word1: '第四学段学生', word2: '音乐表现活动', dependency: '参与' },
        { word1: '第四学段学生', word2: '音乐', dependency: '活动' },
        { word1: '第四学段学生', word2: '富有个性和创意的二度创作及表现形式的创新', dependency: '进行' },
        { word1: '创作', word2: '个性和创意', dependency: '富有' },
        { word1: '创作', word2: '个性和创意', dependency: '创作' },
        { word1: '第四学段学生', word2: '表现形式', dependency: '创新' },
        { word1: '第四学段学生', word2: '创意实践能力和艺术表现水平', dependency: '提高' },
        { word1: '第四学段学生', word2: '创意', dependency: '实践' },
        { word1: '第四学段学生', word2: '创意', dependency: '表现' },
        { word1: '学生', word2: '创意', dependency: '实践' },
        { word1: '第四学段学生', word2: '自信心', dependency: '增强' },
        { word1: '第四学段学生', word2: '自主学习能力和团队合作能力', dependency: '发展' },
        { word1: '第四学段学生', word2: '自主学习能力和团队合作能力', dependency: '学习' },
        { word1: '团队', word2: '自主学习能力和团队合作能力', dependency: '合作' },
        { word1: '第四学段学生', word2: '比较完整的短小音乐作品', dependency: '编创' },
        { word1: '第四学段学生', word2: '比较完整的短小音乐作品', dependency: '展示' },
        { word1: '音乐作品', word2: '比较完整的短小音乐作品', dependency: '完整' },
        { word1: '第四学段学生', word2: '自己的想法和情 感', dependency: '表达' },
        { word1: '第四学段学生', word2: '较丰富的想象力和创造力', dependency: '具有' },
        { word1: '第四学段学生', word2: '想象力和创造力', dependency: '丰富' },
        { word1: '第四学段学生', word2: '中国音乐文化', dependency: '热爱' },
        { word1: '第四学段学生', word2: '民族文化智慧', dependency: '汲取' },
        { word1: '第四学段学生', word2: '文化自 信', dependency: '坚定' },
        { word1: '第四学段学生', word2: '世界音乐文化的多样性', dependency: '领略' },
        { word1: '第四学段学生', word2: '不同音乐的表达方式', dependency: '包容' },
        { word1: '第四学段学生', word2: '文 化差异', dependency: '尊重' },
        { word1: '第四学段学生', word2: '不同艺术的主要表现形式、表现手段和审美特征', dependency: '认识' },
        { word1: '第四学段学生', word2: '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用', dependency: '理解' },
        { word1: '人类', word2: '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用', dependency: '生活' },
        { word1: '人类', word2: '音 乐与其他学科，以及人类生活、社会发展等方面的紧密联系和相互作用', dependency: '发展' },
        { word1: '第四学段学生', word2: '美术产生的背景及不同时代、地区、民族和国家的美术特 征', dependency: '了解' },
        { word1: '美术', word2: '美术产生的背景及不同时代、地区、民族和国家的美术特 征', dependency: '产生' },
        { word1: '第四学段学生', word2: '开放包容的心态和人类命运共同体意识', dependency: '知道' },
        { word1: '美术作品', word2: '中华民族追求独立解放和党团结带领人民进行革命、建设、改革', dependency: '反映' },
        { word1: '中华民族', word2: '独立解放', dependency: '追求' },
        { word1: '党', word2: '美术作品', dependency: '团结' },
        { word1: '美术作品', word2: '人民进行革命、建设、改革', dependency: '带领' },
        { word1: '党', word2: '革命、建设、改革', dependency: '进行' },
        { word1: '党', word2: '革命、建设、改革', dependency: '革命' },
        { word1: '党', word2: '革命、建设、改革', dependency: '建设' },
        { word1: '党', word2: '革命、建设、改革', dependency: '改革' },
        { word1: '党', word2: '对伟 大祖国、中华民族的情感', dependency: '增强' },
        { word1: '党', word2: '红色基因', dependency: '传承' },
        { word1: '党', word2: '文化自信', dependency: '坚定' },
        { word1: '党', word2: '文化自信', dependency: '形成' },
        { word1: '第四学段学生', word2: '平面、立体或动态等表现形式的美术作品', dependency: '创作' },
        { word1: '第四学段学生', word2: '对自然与社会的感受、思考和认识', dependency: '达' },
        { word1: '第四学段学生', word2: '创造性思维能力', dependency: '发展' },
        { word1: '第四学段学生', word2: '“设计满足实用功能与审美价值，传递社会责任”的设计原则', dependency: '了解' },
        { word1: '设计', word2: '实用功能与审美价值', dependency: '满足' },
        { word1: '设计', word2: '社会责任', dependency: '传递' },
        { word1: '学校或社区', word2: '社会责任', dependency: '学习' },
        { word1: '学校或社区', word2: '社会责任', dependency: '需求' },
        { word1: '学生', word2: '作品', dependency: '设计' },
        { word1: '学生', word2: '学段学生', dependency: '形成' },
        { word1: '学生', word2: '社会责任感', dependency: '增强' },
        { word1: '第四学段学生', word2: '非物质文化遗产的含义', dependency: '了解' },
        { word1: '第四学段学生', word2: '传统工艺品或文创产品', dependency: '制作' },
        { word1: '第四学段学生', word2: '继承与发展文化遗产是我们的责任', dependency: '认 识' },
        { word1: '第四学段学生', word2: '文化遗产', dependency: '继承' },
        { word1: '第四学段学生', word2: '文化遗产', dependency: '发展' },
        { word1: '继承与发展文化遗产', word2: '我们的责任', dependency: '是' },
        { word1: '第四学段学生', word2: '美术对个人发展、社会进步及构建人类命运共同体具有独 特的作用', dependency: '理解' },
        { word1: '第四学段学生', word2: '个人', dependency: '发展' },
        { word1: '社会', word2: '个人', dependency: '进步' },
        { word1: '社会', word2: '人类命运共同体', dependency: '构建' },
        { word1: '美术', word2: '独 特的作用', dependency: '具有' },
        { word1: '作用', word2: '独 特的作用', dependency: '独 特' },
        { word1: '第四学段学生', word2: '综合探索与学习迁移的能力', dependency: '提升' },
        { word1: '第四学段学生', word2: '综合探索与学习迁移的能力', dependency: '探索' },
        { word1: '第四学段学生', word2: '不同体裁和风格的舞蹈', dependency: '了解' },
        { word1: '第四学段学生', word2: '舞蹈美的丰富性', dependency: '感受' },
        { word1: '第四学段学生', word2: '不同舞种的舞蹈姿态与基本动作', dependency: '掌握' },
        { word1: '第四学段学生', word2: '身体语言', dependency: '运用' },
        { word1: '第四学段学生', word2: '创意', dependency: '有' },
        { word1: '第四学段学生', word2: '不同体裁和风格的舞蹈', dependency: '表现' },
        { word1: '第四学段学生', word2: '艺术表现能力', dependency: '提升' },
        { word1: '背景', word2: '艺术表现能力', dependency: '不同' },
        { word1: '第四学段学生', word2: '中外舞蹈艺术特色', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '中外舞蹈艺术特色', dependency: '分析' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化的学习与传承', dependency: '加强' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化', dependency: '学习' },
        { word1: '第四学段学生', word2: '对我国优秀民族舞蹈文化', dependency: '传承' },
        { word1: '学生', word2: '文化自信', dependency: '坚定' },
        { word1: '第四学段学生', word2: '多种艺术表现形式', dependency: '运用' },
        { word1: '第四学段学生', word2: '多种艺术表现形式', dependency: '合作' },
        { word1: '第四学段学生', word2: '情感、观念和想象', dependency: '表达' },
        { word1: '第四学段学生', word2: '舞蹈', dependency: '编排' },
        { word1: '第四学段学生', word2: '舞蹈', dependency: '实践' },
        { word1: '第四学段学生', word2: '创新思维能力', dependency: '提升' },
        { word1: '第四学段学生', word2: '戏剧编演的方法', dependency: '了解' },
        { word1: '第四学段学生', word2: '戏剧', dependency: '编演' },
        { word1: '第四学段学生', word2: '运用多种艺术手段进行戏剧演出的基本能力', dependency: '具有' },
        { word1: '第四学段学生', word2: '多种艺术手段', dependency: '运用' },
        { word1: '第四学段学生', word2: '戏剧演出', dependency: '进行' },
        { word1: '第四学段学生', word2: '戏剧', dependency: '演出' },
        { word1: '第四学段学生', word2: '戏曲', dependency: '含' },
        { word1: '学生', word2: '初步欣赏和分析', dependency: '进行' },
        { word1: '第四学段学生', word2: '对戏剧（含戏曲）艺术作品', dependency: '欣赏' },
        { word1: '第四学段学生', word2: '对戏剧（含戏曲）艺术作品', dependency: '分析' },
        { word1: '第四学段学生', word2: '初步表达观剧感受和见解的能力', dependency: '具有' },
        { word1: '第四学段学生', word2: '观剧感受和见解', dependency: '表达' },
        { word1: '第四学段学生', word2: '剧', dependency: '观' },
        { word1: '第四学段学生', word2: '第四学段学生', dependency: '形成' },
        { word1: '第四学段学生', word2: '“教育戏剧”“教育剧场”的方法', dependency: '了解' },
        { word1: '第四学段学生', word2: '一定的戏剧应 用活动', dependency: '进行' },
        { word1: '第四学段学生', word2: '一定的戏剧应 用活动', dependency: '活动' },
        { word1: '第四学段学生', word2: '中外戏剧艺术史的基本常识', dependency: '掌握' },
        { word1: '第四学段学生', word2: '中外戏剧艺术的不 同文化背景', dependency: '认识' },
        { word1: '第四学段学生', word2: '中国戏曲艺术所具有的独特的审美特征', dependency: '了解' },
        { word1: '中国戏曲艺术', word2: '审美特征', dependency: '具有' },
        { word1: '审美特征', word2: '审美特征', dependency: '独特' },
        { word1: '第四学段学生', word2: '文化自信', dependency: '坚 定' },
        { word1: '第四学段学生', word2: '戏剧（含戏曲）活动', dependency: '参与' },
        { word1: '第四学段学生', word2: '戏曲', dependency: '活动' },
        { word1: '第四学段学生', word2: '与同伴合作的意识和团队精神', dependency: '养成' },
        { word1: '与同伴', word2: '与同伴合作的意识和团队精神', dependency: '合作' },
        { word1: '与同伴', word2: '脚本', dependency: '创编' },
        { word1: '与同伴', word2: '剧目', dependency: '演出' },
        { word1: '与同伴', word2: '对他人及自我的理解', dependency: '增进' },
        { word1: '与同伴', word2: '对他人及自我', dependency: '理解' },
        { word1: '与同伴', word2: '身心健康成长', dependency: '促进' },
        { word1: '身心', word2: '身心健康成长', dependency: '成长' },
        { word1: '身心', word2: '身心健康成长', dependency: '活动' },
        { word1: '身心', word2: '社会主义核心价值观', dependency: '树立' },
        { word1: '身心', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '传承' },
        { word1: '身心', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '弘扬' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）与真实世界、虚拟世界的联系', dependency: '建立' },
        { word1: '第四学段学生', word2: '数字媒体艺术', dependency: '含' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）与真实世界、虚拟世界', dependency: '联系' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的形态特征', dependency: '把握' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）的基本创作技巧和艺术语言', dependency: '掌握' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）', dependency: '创作' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的制作流程', dependency: '了解' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品', dependency: '制作' },
        { word1: '第四学段学生', word2: '简单的数字设备和软件', dependency: '运用' },
        { word1: '数字设备和软件', word2: '简单的数字设备和软件', dependency: '简单' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品', dependency: '创作' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）作品的主要类型、风格与流派', dependency: '了解' },
        { word1: '第四学段学生', word2: '简单评述', dependency: '进行' },
        { word1: '第四学段学生', word2: '对影视（含数字媒体艺术）作品', dependency: '评述' },
        { word1: '第四学段学生', word2: '影视（含数字媒体艺术）在传承和弘扬中华优秀传统文化、革命文化、社会主义先 进文化，感悟伟大建党精神过程中的重要作用', dependency: '认识' },
        { word1: '第四学段学生', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '传承' },
        { word1: '第四学段学生', word2: '中华优秀传统文化、革命文化、社会主义先 进文化', dependency: '弘扬' },
        { word1: '第四学段学生', word2: '伟大建党精神', dependency: '感悟' },
        { word1: '第四学段学生', word2: '其他艺术学科，以及信息科技等课程', dependency: '学习' },
        { word1: '第四学段学生', word2: '学科，以及信息科技等课程的学习', dependency: '结合' },
        { word1: '第四学段学生', word2: '综合融通', dependency: '进行' },
        { word1: '第四学段学生', word2: '影视艺术思维、数字媒体思维、信息思维和科技思维等', dependency: '综合' },
        { word1: '第四学段学生', word2: '影视艺术思维、数字媒体思维、信息思维和科技思维等', dependency: '融通' },
        { word1: '第四学段学生', word2: '创意活动', dependency: '开展' },
        { word1: '第四学段学生', word2: '审美和人文素养', dependency: '提升' },
        { word1: '艺术', word2: '第一学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第二学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第三学段学生', dependency: '阶段' },
        { word1: '艺术', word2: '第四学段学生', dependency: '阶段' },
      ],
    }
  },
}
</script>

<style></style>
